### ISSUE TITLE
Expose Starlette options

### ISSUE THREAD

**Issue by tr11** [aminalaee/sqladmin#113]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

It'd be great to expose the `middleware` and `debug` parameters to pass to the Starlette admin app. This would allow, for example, to create a middleware that checks for an "admin" session cookie and redirect the user in case the cookie doesn't exist.  The debug option is useful when developing.

**Comment by aminalaee** [comment]
Thank you for the suggestion and PR, this is already merged.
