### ISSUE TITLE
Demo page crashing

### ISSUE THREAD

**Issue by dionysio** [aminalaee/sqladmin#117]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

https://python-sqladmin.herokuapp.com/admin/ shows generic Server error heroku page.

### Environment

- web

**Comment by aminalaee** [comment]
Hey, thanks for reporting this 👍 

Looks like I've exceeded the free plan, I'll try to upgrade it soon.
