### ISSUE TITLE
sort doesn't work after adding custom labels.

### ISSUE THREAD

**Issue by nazmulnnb** [aminalaee/sqladmin#118]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Thank you for this awesome repo. It saved me a lot of time.
I have faced a weird bug. 
Here goes my model.
` class UserAdmin(ModelAdmin, model=UserModel.User):`
    `column_list = [UserModel.User.id, UserModel.User.last_name, UserModel.User.first_name, UserModel.User.email]`
    `column_sortable_list = [UserModel.User.last_name,UserModel.User.first_name,UserModel.User.email]`
    `column_labels = dict(id='ID',last_name='Last Name', first_name='First Name',email='Email Address')`

It worked perfectly until I added custom_labels. Now when ever I click on the table header, it returns with an error saying "Model User has no attribute 'Email address' "

This should sort using original field name, not with the label.

### Environment

- OS: ubuntu 20.04
- python 3.7.10
- fastapi 0.63
- sqladmin 0.1.7
- SQLAlchemy 1.4.32

**Comment by aminalaee** [comment]
Hey, thanks for reporting this.
I think the title should be `sort` does not work, not search does not work. Right?

I'll take a look into this.

**Comment by nazmulnnb** [comment]
Sorry. updated the title.
Also, what is the correct way to encrypt the password when creating a new user?
current system is saving the password without encryption. 
Thanks you.

**Comment by aminalaee** [comment]
SQLAdmin doesn't deal with User or Password. You can implement whatever authentication system you want on it.

**Comment by aminalaee** [comment]
SQLAdmin doesn't deal with User or Password. You can implement whatever authentication system you want on it.

**Comment by aminalaee** [comment]
Ah, sorry I get that now.

There was a similar discussion about this, one option is to override the whole `create` method so that you can create your User with your own logic.
It's not ready yet.
