### ISSUE TITLE
Link to relationship

### ISSUE THREAD

**Issue by badger-py** [aminalaee/sqladmin#124]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Add auto link in relationship. As example: https://python-sqladmin.herokuapp.com/admin/address/details/1 to get user I need to go to table users, find user(no search). Please make user_id a link to users

### Describe the solution you would like.

user_id is a link to users

**Comment by aminalaee** [comment]
Yes that makes sense.
 But I think instead of linking user_id link to User page, we shoud link "user" because that's the relationship.

**Comment by aminalaee** [comment]
This is done and will be available in the next release.
