### ISSUE TITLE
Ability to choose format of datetimes in list/table view

### ISSUE THREAD

**Issue by lovetoburnswhen** [aminalaee/sqladmin#131]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Currently the values for datetime columns seem to be rendered as ISO-8601 with millisecond precision which is unnecessary (eg `2022-04-04 22:43:30.027151`)

### Describe the solution you would like.

It'd be great if we had a way to pass some sort of custom formatter, ideally a callable that takes the DB value and returns the value that should be passed to the renderer.

**Comment by aminalaee** [comment]
I think this can generally be achieved with `column_formatters` here: https://flask-admin.readthedocs.io/en/latest/api/mod_model/#flask_admin.model.BaseModelView.column_formatters

Feel free to create PRs for that.
