### ISSUE TITLE
Now the json field is only for viewing and printing. Automatic generation is needed.

### ISSUE THREAD

**Issue by wnesbv** [aminalaee/sqladmin#139]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

There are:
class JSONField(fields.TextAreaField):
Necessary:
class JSONField(fields.FileField):

### Describe the solution you would like.

In the web forms I have configured https://accent-starlette.github.io/starlette-files/handling_files/
file = sa.Column(FileType.as_mutable(sa.JSON), nullable=True)
[views.py](https://github.com/wnesbv/starlette-all/blob/main/item/views.py)
The result is excellent
In the admin area of the coma

### Describe alternatives you considered

Alternative solution: I have not found.

### Additional context

Now the json field is only for viewing and printing. Automatic generation is needed.

**Comment by aminalaee** [comment]
Hey @wnesbv 
Can you please explain what you mean by that? I don't really understand what you mean by "automatic generation".

**Comment by aminalaee** [comment]
We can re-open with more info.
