### ISSUE TITLE
Used Sqlalchemy_utils types

### ISSUE THREAD

**Issue by colin99d** [aminalaee/sqladmin#148]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

I want to be able to use model types provided by sqlalchemy_utils such as EmailType, IPAddressType, and UUIDType.

### Describe the solution you would like.

I would like the admin page to work without crashing when they are used (just treating them all as strings would work fine for me).

### Describe alternatives you considered

I could convert them all to strings in my model, but that would take away a lot of functionality.

**Comment by aminalaee** [comment]
Hi,

Yes I think that's been requested before, feel free to create a PR for it if you're interested.
The change is straightforward and needs to be added here: https://github.com/aminalaee/sqladmin/blob/main/sqladmin/forms.py#L318

**Comment by colin99d** [comment]
Will do this once I get some down time!
