### ISSUE TITLE
There is no way to customize object_list for form_args.

### ISSUE THREAD

**Issue by dasaderto** [aminalaee/sqladmin#151]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

I want to set up a custom objects_list for the QuerySelectField field, but I can't because this property is overridden in the ModelConverter.convert method.

**Comment by aminalaee** [comment]
Hey, thank you for the feedback.
Can you provide your use-case? Why do you need this?

**Comment by dasaderto** [comment]
> Hey, thank you for the feedback.
> Can you provide your use-case? Why do you need this?

For example, I want to allow only certain values ​​to be set in a related form field.  To do this, I had to pull out a piece of code from the library, and remove this redefinition

**Comment by aminalaee** [comment]
Yeah that makes sense, feel free to create a PR to remove this limitation.

**Comment by aminalaee** [comment]
@dasaderto Hey, the PR will that, it would be great if you could take a look.
