### ISSUE TITLE
Datetime field can't choose from panel

### ISSUE THREAD

**Issue by ischaojie** [aminalaee/sqladmin#169]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I used `SQLAdmin` in my personal project(That's awesome 🥳), But the datetime field need to enter manually:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/12986082/172055848-4ce4a21b-fd6d-4250-ac3f-e502da02691d.png">

Maybe choose from panel is better:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/12986082/172055878-9d26333d-64aa-47ab-a9b7-ead495ae8b41.png">

### Environment

os: mac
python: 3.9
sqladmin: lastest

**Comment by ischaojie** [comment]
It's better to use `datetime-local`:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

**Comment by aminalaee** [comment]
Hey, thanks for reporting this.

I think maybe a better approach would be to use a Bootstrap DateTime picker and not depend on the browser supports? What do you think?

If you also would like feel free to make a PR for it.

**Comment by aminalaee** [comment]
BTW, what browser and what version are you using?

**Comment by ischaojie** [comment]
> BTW, what browser and what version are you using?

I using chrome 102.0.5005.61

**Comment by aminalaee** [comment]
hmm.I'm using chrome 101.x.x and it's working alright. weird though.

**Comment by ischaojie** [comment]
Weird, the code is like this:
```python
class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    name = Column(String)
    age = Column(Integer)
    created_at = Column(DateTime, default=datetime.now())


Base.metadata.create_all(engine)  # Create tables

app = FastAPI()
admin = Admin(app, engine)


class UserAdmin(ModelAdmin, model=User):
    column_list = [User.id, User.name, User.age]


admin.register_model(UserAdmin)
```

**Comment by ischaojie** [comment]
> Even here it says it should be supported: [caniuse.com/input-datetime](https://caniuse.com/input-datetime)

But it's the `type="datetime-local"` supported, not `type="datetime"`

<img width="830" alt="image" src="https://user-images.githubusercontent.com/12986082/172414478-0e3bfaef-7753-4fe3-9bf4-fdd0370ff102.png">

**Comment by ischaojie** [comment]
I noticed `tabler` use `litepicker` as date form picker, But😑:

https://github.com/tabler/tabler/issues/1136

**Comment by aminalaee** [comment]
@ischaojie Can we still use litepicker and then switch to the new one when tabler switches?

**Comment by ischaojie** [comment]
> @ischaojie Can we still use litepicker and then switch to the new one when tabler switches?

`litepicker` didn't support choosing `time`, but new [easepick](https://easepick.com/) supports it.

see: https://github.com/wakirin/Litepicker/issues/1

Or use another lib.

**Comment by aminalaee** [comment]
Added flatpickr to handle Date and DateTimes: https://github.com/aminalaee/sqladmin/pull/288
