### ISSUE TITLE
Readonly column support

### ISSUE THREAD

**Issue by okapies** [aminalaee/sqladmin#178]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

It is useful if `ModelAdmin` has a setting like `form_readonly_columns` that specifies columns the users can not edit.

### Additional context

The author of wtforms recommends [just remove the "read-only" field from the input](https://github.com/wtforms/wtforms/issues/217#issuecomment-164653572) before storing them to the DB.

**Comment by aminalaee** [comment]
@okapies Thanks for the suggestion.
I think this can be achieved with this:

```python
class Admin(...):
    form_widget_args = { 'email':{ 'readonly':True } }
```

We can also add the new configuration as you mentioned, but I'm not sure about it at the moment.

**Comment by okapies** [comment]
I tried but it doesn't work for me. I need to use `form_args` instead:

```python
class Admin(...):
    form_args = {
        "email": {"render_kw": {"readonly": True}},
    }
```

**Comment by aminalaee** [comment]
Closing this for now as there are already two solutions mentioned.

**Comment by Rivosoa** [comment]
How do I make a column editable in "Create" page but readonly in "Edit" page?

**Comment by aryadovoy** [comment]
@Rivosoa, have you found the solution?

**Comment by Rivosoa** [comment]
> @Rivosoa, have you found the solution?

Unfortunately I haven't found the solution.

**Comment by Dimaz55** [comment]
@Rivosoa , @aryadovoy
`async def get_object_for_edit(self, value: Any) -> Any:
    self.__class__.form_widget_args = {"code": {"readonly": True}}
    return await super().get_object_for_edit(value)`
