### ISSUE TITLE
`column_formatters` doesn't work with one-to-many relation

### ISSUE THREAD

**Issue by okapies** [aminalaee/sqladmin#196]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

The details page fails to render the list value formatted by `column_formatters` and `column_formatters_detail` because the following template tries to pass it to `_url_for_details()` instead of the original model value.

https://github.com/aminalaee/sqladmin/blob/83d8d2540f8a0fdca1e23ae35e37580b6dec06e6/sqladmin/templates/details.html#L24-L26

### Steps to reproduce the bug

```python
from typing import List

from sqlalchemy import Column, ForeignKey, Integer, create_engine
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
engine = create_engine(...)


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    addresses: List["Address"] = relationship("Address", back_populates="user")


class Address(Base):
    __tablename__ = "addresses"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    user: User = relationship("User", back_populates="addresses")


Base.metadata.create_all(engine)
```

```python
from fastapi import FastAPI
from sqladmin import Admin, ModelAdmin

app = FastAPI()
admin = Admin(app, engine)


class UserAdmin(ModelAdmin, model=User):
    column_list = [User.id, User.address]
    column_formatters = {
        User.addresses: lambda m, a: [a.id for a in m.addresses],
    }


admin.register_model(UserAdmin)
```

### Debugging material

```python
  File "/myproject/.venv/lib/python3.9/site-packages/sqladmin/templates/details.html", line 25, in block 'content'
    <a href="{{ model_admin._url_for_details(value) }}">({{ value }})</a>
  File "/myproject/.venv/lib/python3.9/site-packages/sqladmin/models.py", line 567, in _url_for_details
    pk = getattr(obj, inspect(obj).mapper.primary_key[0].name)
  File "/myproject/.venv/lib/python3.9/site-packages/sqlalchemy/inspection.py", line 71, in inspect
    raise exc.NoInspectionAvailable(
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'str'>
```

### Environment

- Ubuntu 20.04.4 LTS
- Python 3.9.12
- SQLAdmin 0.1.9

**Comment by aminalaee** [comment]
Hey,

Yeah I think this is the trade-off, if we want to link to details page by default (as it is currently) then we can't allow formatting it.
Maybe we can check if no formatter is specified then we can do default formatting.

**Comment by okapies** [comment]
Hmm, I just need links for each child record with pretty printed name (instead of implementing `__repr__`). It is useful if we make `get_detail_value()` return, for example, a tuple like `(value, formatted)` and the details render the value by using it. What do you think?

**Comment by okapies** [comment]
Another solution is that the page renders a link to the corresponding admin page with the appropriate parameter (e.g. `/admin/addresses/list?user_id=1`). It seems it is useful for a model with large child items.
