### ISSUE TITLE
the online demo application error

### ISSUE THREAD

**Issue by ischaojie** [aminalaee/sqladmin#213]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

<img width="526" alt="image" src="https://user-images.githubusercontent.com/12986082/175764199-57e4b9b2-5272-4d67-b10c-dc0dc09d3a33.png">

### Environment

- None

**Comment by aminalaee** [comment]
Thanks, I'll update that.
