### ISSUE TITLE
Customizable query for search and filter

### ISSUE THREAD

**Issue by phap-aimfirst** [aminalaee/sqladmin#216]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Hi,
There are 2 problems but they have relations and can be considered as one:
1- I would like to configure the query for the search box. Currently it is generated automatically by the admin code.
But when I want to search by JSON field it crashed
Or when I want to fine tune my search for example for some fields it is "equal", for other fields it is "like", for anothers it is "has", ... I have no way to do that

2- In the list, I'd like to have a way to filter my models and not give out everything but just those models which satisfy some filter criteria.
For example in my user table I have 2 user types: student and teacher. Now I want to create 2 separate menus: Teachers  and Students for these objects

### Describe the solution you would like.

Can customize query to select items in list: query, query_count
Can filter items return by list by specifying field value

**Comment by aminalaee** [comment]
Hey, thanks for the suggestion, I think they are possible, you can override ModelAdmin methods:
https://github.com/aminalaee/sqladmin/blob/daea8c9c385794605ddeb02b7105d71ca9a9823f/sqladmin/models.py#L670

```python
class UserAdmin(ModelAdmin, model=User):
    async def list(
        self,
        page: int,
        page_size: int,
        search: Optional[str] = None,
        sort_by: Optional[str] = None,
        sort: str = "asc",
    ) -> Pagination:
        ...
```

The only drawback I can think of can be that you always have to switch between sync and async and providing an API for query might be nicer, something like you said:

```python
class UserAdmin(ModelAdmin, model=User):
    list_query = select(User).filter(User.active=True)
```

But I think this won't be possible for the search, I have to  give it some thought.
