### ISSUE TITLE
`sourceMappingURL` triggers access to non-existent file

### ISSUE THREAD

**Issue by okapies** [aminalaee/sqladmin#218]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

The .js files specify `sourceMappingURL` but the `.map` files are not included in the package. So the browser tries to fetch it and gets a 404 error. We should add the source map files or remove the following lines:

https://github.com/aminalaee/sqladmin/blob/daea8c9c385794605ddeb02b7105d71ca9a9823f/sqladmin/statics/js/bootstrap.min.js#L7

### Debugging material

```
INFO:     127.0.0.1:8000 - "GET /js/bootstrap.min.js.map HTTP/1.1" 404 Not Found
```

### Environment

- Ubuntu 20.04.4 LTS
- Python 3.9.12
- SQLAdmin 0.1.11

**Comment by ischaojie** [comment]
Or just use the CDN link 😀

**Comment by okapies** [comment]
I think using the CDN has some downsides:

- The site will be unavailable if the CDN is down
- Security consideration
