### ISSUE TITLE
SQLAdmin crashes when table has a column of unsupported type, even if the column is not mapped to SQLAdmin

### ISSUE THREAD

**Issue by oryba** [aminalaee/sqladmin#233]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When a table has an unused column of a type which has no appropriate converter, SQLAdmin crashes. The column isn't mapped to SQLAdmin in any way, so I believe it shouldn't be converted (and even selected at all).

In my case there's a TSVECTOR column for search outside the admin panel. It's generated, no need to manage it directly.

If you agree that's a bug, I can try creating a PR to fix that. And I'd even suggest to provide an interface for adding custom converters, that would in addition make it easier to deal with issues like #215

### Steps to reproduce the bug

```
class TestModel(Base):
    __tablename__ = "test_model"

    catalog_num = Column(String, primary_key=True)
    name = Column(String)
    index = Column(TSVECTOR, Computed("to_tsvector('english', name || ' ' || catalog_num)"))

    __table_args__ = (
        Index(
            'idx_search_fts',
            index,
            postgresql_using='gin'
        ),
    )
```

And admin declaration looks like:

```
class TestAdmin(ModelAdmin, model=TestModel):
    column_list = [TestModel.catalog_num, TestModel.name]
    column_details_list = [TestModel.catalog_num, TestModel.name]
    form_include_pk = True
```

### Expected behavior

SQLAdmin never selects this column and doesn't try to convert it anyhow

Actually I could duct tape this by adding

```
def conv_text(
        *args, **kwargs
):
    return


def conv(self) -> None:
    converters = {'TSVECTOR': conv_text}

    for name in dir(self):
        obj = getattr(self, name)
        if hasattr(obj, "_converter_for"):
            for classname in obj._converter_for:
                converters[classname] = obj

    self._converters = converters


ModelConverterBase._register_converters = conv
```

### Actual behavior

SQLAdmin crashes when opening details pane on UI

### Debugging material

```
  File "/Users/whatever/venvs/test/lib/python3.9/site-packages/sqladmin/application.py", line 352, in edit
    Form = await model_admin.scaffold_form()
  File "/Users/whatever/venvs/test/lib/python3.9/site-packages/sqladmin/models.py", line 909, in scaffold_form
    return await get_model_form(
  File "/Users/whatever/venvs/test/lib/python3.9/site-packages/sqladmin/forms.py", line 470, in get_model_form
    field = await converter.convert(
  File "/Users/whatever/venvs/test/lib/python3.9/site-packages/sqladmin/forms.py", line 256, in convert
    converter = self.get_converter(prop=prop)
  File "/Users/whatever/venvs/test/lib/python3.9/site-packages/sqladmin/forms.py", line 224, in get_converter
    raise NoConverterFound(  # pragma: nocover
sqladmin.exceptions.NoConverterFound: Could not find field converter for column index (<class 'sqlalchemy.dialects.postgresql.base.TSVECTOR'>).
```

### Environment

 - Python 3.9
 - SQLAlchemy 1.4.39
 - sqladmin 0.1.11

**Comment by aminalaee** [comment]
Hey, thanks for taking a look into this.

I think the first issue is here:
```python
class TestAdmin(ModelAdmin, model=TestModel):
    column_list = [TestModel.catalog_num, TestModel.name]
    column_details_list = [TestModel.catalog_num, TestModel.name]
    form_include_pk = True
```

You don't specify `form_columns` and the issue is that by default `form_columns` will use all columns without a default value. And then it tries to find a converter for it for the form and as you said it fails.

The options `column_` are for displaying data and options with `form_` are related to forms.

> And I'd even suggest to provide an interface for adding custom converters, that would in addition make it easier to deal with issues like https://github.com/aminalaee/sqladmin/issues/215

And about this I think later we can add a converter but right we have most of the column types, so it should be fine.
And that ticket you mentioned, AFAIK is more related to the search functionality over JSON, because JSON support is already there.

**Comment by oryba** [comment]
Hey, thanks for a quick reply! Just tried to whitelist columns with `form_columns` - works fine now. I thought `column_details_list` limits whatever appears in the details when creating/editing\deleting.

I believe the issue can be closed then. Thank you for this cool project:)
