### ISSUE TITLE
Custom page creation

### ISSUE THREAD

**Issue by aminalaee** [aminalaee/sqladmin#237]
### Discussed in https://github.com/aminalaee/sqladmin/discussions/236

<div type='discussions-op-text'>

<sup>Originally posted by **masksshow** July 12, 2022</sup>
Hello.
Can I add a custom page to the menu? It is not related to the model.
For example, a statistics page or a custom template.</div>

**Comment by just-an-dev** [comment]
I also looking for that, and I look a bit how to do it. 
@aminalaee Do you have idea of "best way" to do that ?
Adding some parameters/method to BaseAdmin to only add it in menu the "route" can be a good start maybe ?

**Comment by just-an-dev** [comment]
I have something working, but I need to look how refactoring to be clean. And remove FastAPI dependency.

**Comment by aminalaee** [comment]
Cool, feel free to create a PR for it.

**Comment by just-an-dev** [comment]
I just open one to have "feedback" and talk on how to do it in clean way, because it's very ugly 😂

**Comment by aminalaee** [comment]
Thanks to @just-an-dev This is merged and will be in `0.2.0` release
