### ISSUE TITLE
Hide admin page for unauthorized users

### ISSUE THREAD

**Issue by bralbral** [aminalaee/sqladmin#252]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

According [documentation](https://aminalaee.dev/sqladmin/authentication/) we can use middleware for hiding admin page from some users.

If user is not `is_authenticated` it shows:

![Screenshot from 2022-07-31 16-07-21](https://user-images.githubusercontent.com/54455457/182027963-406bf30b-5856-4469-b30d-dfa6dcd4018b.png)

### Steps to reproduce the bug

Just add auth middleware like this:

```
from sqladmin import Admin, ModelAdmin
from starlette.applications import Starlette
from starlette.requests import Request

# AuthenticationMiddleware explained in Starlette docs

middlewares = [
    Middleware(AuthenticationMiddleware, backend=BasicAuthBackend())
]

app = Starlette()
admin = Admin(app=app, engine=engine, middlewares=middlewares)


class AuthModelAdmin(ModelAdmin):
    def is_accessible(self, request: Request) -> bool:
        # With Authentication backend you can now access request.user.
        if request.user.is_authenticated:
            return True
        return False

```

### Expected behavior

Do not show page; raise error

### Environment

SMP Debian 5.10.106-1 (2022-03-17)
Python 3.9

**Comment by aminalaee** [comment]
Hey, thanks for the suggestion. Yes that makes sense.
The problem is there might be some classes not inheriting from `AuthModelAdmin ` so they might be visible in the page.
There should be a generic way to control this via middlewares maybe. Let me take a look.

**Comment by aminalaee** [comment]
I've added basic support for Authentication in https://github.com/aminalaee/sqladmin/pull/277

I'll update the documentation how to use it, but this will achieve what you want.
