### ISSUE TITLE
"Router" has no attribute "middlerware"

### ISSUE THREAD

**Issue by jockerz** [aminalaee/sqladmin#265]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Log of "./scripts/check"

```
+ venv/bin/isort --check --diff --project=sqladmin sqladmin tests
+ venv/bin/black --check --diff sqladmin tests
All done! ✨ 🍰 ✨
27 files would be left unchanged.
+ venv/bin/flake8 sqladmin tests
+ venv/bin/mypy sqladmin
sqladmin/application.py:321: error: "Router" has no attribute "middlerware"  [attr-defined]
Found 1 error in 1 file (checked 13 source files)
```

### Steps to reproduce the bug

- Clone the repository
- Setup Environment
- Run `./scripts/check`

### Expected behavior

Script complete and success

### Actual behavior

```
+ venv/bin/mypy sqladmin
sqladmin/application.py:321: error: "Router" has no attribute "middlerware"  [attr-defined]
Found 1 error in 1 file (checked 13 source files)
```

### Environment

- Debian GNU/Linux 11 (bullseye) / SQLAdmin git version `origin/main` (`80ce411892585449ec117d4d2491aa42c285216d`)

### Additional context

I think this is a minor bug and SQLAdmin still run well.

**Comment by jockerz** [comment]
I have not yet test or double check, but i the [`sqladmin/application.py:321`](https://github.com/aminalaee/sqladmin/blob/main/sqladmin/application.py#L321) might need to edited to be
```
self.user_middleware = [] if middleware is None else list(middleware)
```

Reference: [starlette/applications.py:75](https://github.com/encode/starlette/blob/master/starlette/applications.py#L75)

**Comment by aminalaee** [comment]
Hmmm, inetersting, can you also include your mypy version?
This is already running in the pipeline without failing.

**Comment by aminalaee** [comment]
Ok happened now in your PR pipeline.

**Comment by jockerz** [comment]
> Hmmm, inetersting, can you also include your mypy version? This is already running in the pipeline without failing.

mypy version
```
mypy                              0.971
mypy-extensions            0.4.3
```

**Comment by jockerz** [comment]
> Unfortunately this will be a bug in middlewares that is not tested, I'll take a look.

Thank you
