### ISSUE TITLE
adding Authentication

### ISSUE THREAD

**Issue by Chise1** [aminalaee/sqladmin#28]

**Comment by aminalaee** [comment]
Yes, some integration with an Authentication backend is definitely a must-have. PRs are welcome though.

**Comment by aminalaee** [comment]
For future references I think integrating with Starlette/FastAPI Authentication backend would be pretty straightforward here.

**Comment by aminalaee** [comment]
Basic Authentication/Authorization functionality is enabled in #37 so we can close this for now.

**Comment by Args** [comment]
Have any more plans for the authorization? It is not very convenient to judge by request now.I don't know what to do if I don't want anyone else to access the data

**Comment by aminalaee** [comment]
Can you please clarify the use-case? I'm not sure if I understand correctly.
There's a PR to allow adding Starlette middlewares to the Admin but I think that will have the same effect.

**Comment by Args** [comment]
Thank you for your reply.That is, I have now deployed the website, anyone who visits https://mysite.com/admin can operate my database, how can I avoid this from happening?

**Comment by aminalaee** [comment]
It is explained here, you can integrate any authentication you want to sqlamin:
https://aminalaee.github.io/sqladmin/authentication/

Does this answer your question?

**Comment by Args** [comment]
What should I do if I want to have a username and password to protect it?

**Comment by aminalaee** [comment]
You can use the Authentication middleware in Starlette: https://www.starlette.io/authentication/

Right now it's not very straightforward after this PR: https://github.com/aminalaee/sqladmin/pull/114

**Comment by Args** [comment]
OK,thanks for your help

**Comment by aminalaee** [comment]
Maybe https://aminalaee.dev/sqladmin/authentication/ ?
