### ISSUE TITLE
sqlalchemy_utils types

### ISSUE THREAD

**Issue by aminalaee** [aminalaee/sqladmin#282]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Need to complete the rest of sqlalchemy_utils types like ColorType, JSONType, PasswordType, ...

**Comment by kupavel87** [comment]
Hi @aminalaee 
Is there any workaround until this fix is made?
e.g. custom or default converter for sqlalchemy_utils, geoalchemy2 etc.

**Comment by aminalaee** [comment]
@kupavel87 I haven't really tried to use this before but I think `form_overrides` should do that: https://aminalaee.dev/sqladmin/configurations/#form-options

**Comment by garzillo** [comment]
Here's an example of how to do this for `ScalarListType` and `JSONType` fields from `sqlalchemy_utils`:

```
import json
from wtforms.fields import Field
from wtforms.widgets import TextInput
from sqladmin import ModelView


class JSONField(Field):
    widget = TextInput()

    def _value(self):
        return json.dumps(self.data) if self.data else ''

    def process_formdata(self, valuelist):
        if valuelist:
            try:
                self.data = json.loads(valuelist[0])
            except ValueError:
                raise ValueError('This field contains invalid JSON')
        else:
            self.data = None

    def pre_validate(self, form):
        super().pre_validate(form)
        if self.data:
            try:
                json.dumps(self.data)
            except TypeError:
                raise ValueError('This field contains invalid JSON')


class ListField(Field):
    widget = TextInput()

    def _value(self):
        if self.data:
            return u', '.join(self.data)
        else:
            return u''

    def process_formdata(self, valuelist):
        if valuelist:
            self.data = [x.strip() for x in valuelist[0].split(',')]
        else:
            self.data = []


class CoolModelAdmin(ModelView, model=CoolModel):
    form_overrides = dict(
        my_json_field=JSONField,
        my_list_field=ListField
    )
```

**Comment by aditkumar72** [comment]
Hi @aminalaee, Is this issue still relevant ? If yes, I will be happy to work on it.

**Comment by aminalaee** [comment]
@aditkumar72 Yeah sure.
Just be aware to not include those types which have composite sqlalchemy types (for now) as they are not supported.

**Comment by aminalaee** [comment]
added in https://github.com/aminalaee/sqladmin/pull/422
