### ISSUE TITLE
Making navbar collapse on small screens

### ISSUE THREAD

**Issue by aminalaee** [aminalaee/sqladmin#283]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

In large screen:
<img width="1597" alt="Screenshot 2022-08-26 at 09 00 45" src="https://user-images.githubusercontent.com/19784933/186842573-d9806d3c-a74e-46cd-9bcd-4329054f0651.png">

In small screen:
<img width="499" alt="Screenshot 2022-08-26 at 09 00 56" src="https://user-images.githubusercontent.com/19784933/186842586-faffa25f-48b2-4a45-b9f9-d6b743a1404f.png">

The navbar is lost and it might be useful to make this responsive.

**Comment by su-shubham** [comment]
Yes the navbar is not showing in small screen.might have to add toggle or something that can be helpful when working on small screen using css.

**Comment by aminalaee** [comment]
We're actually using Bootstrap and TablerUI so they are supported out of the box, we just need to use the correct css classes to support this.
