### ISSUE TITLE
When adding None as choice in SelectField, in database there is 'None' instead of NULL value

### ISSUE THREAD

**Issue by patrykko-intel** [aminalaee/sqladmin#301]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When add None as choice in SelectField in database there is 'None' instead of NULL value.

Example:
class IpxeScriptAdmin(ModelAdmin, model=Model):

    column_list = [
        Model.id,
        Model.name,
        IpxeScript.default,
    ]
    form_overrides = {
        'default': SelectField,
    }
    form_args = {
        'default': {
            'choices': ['val1', None]
        }
    }

### Steps to reproduce the bug

Create above Model and selec None in form.

### Expected behavior

There should be NULL in database.

### Actual behavior

There is 'None' string in database.

### Environment

Python3.8, sqladmin 0.4.0, PostgreSQL 14.2

**Comment by aminalaee** [comment]
That's the wtforms behaviour. If you want SQLAdmin to handle that you can probably create an Enum or use sqladmin `SelectField` instead of that.
