### ISSUE TITLE
Error when sorting with the label

### ISSUE THREAD

**Issue by GitBib** [aminalaee/sqladmin#304]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When a field is sorted and has a specified label, the following error occurs: `sqlalchemy.exc.CompileError: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'Company type' should be explicitly declared as text('Company type')`.

### Environment

Python3.10, sqladmin 0.4.0, PostgreSQL 14.1

**Comment by aminalaee** [comment]
Closed by #305
