### ISSUE TITLE
X-Forwarded-Host support

### ISSUE THREAD

**Issue by jsmolina** [aminalaee/sqladmin#307]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

If sqladmin is served behind a proxy, X-Forwarded-Host should be honored:
curl http://localhost:8001/sqladmin/login -H "X-Forwarded-Host: foo.bar"

But generated HTML is requesting to original Host instead:
"http://localhost:8001/sqladmin/statics/js/main.js"

### Describe the solution you would like.

Support for x-forwarded-host (and proto) should be included so it will work properly behind a proxy.

### Describe alternatives you considered

There are many alternatives:
-  a middleware,
-  generate static urls in a relative manner.
- ..

**Comment by aminalaee** [comment]
Hey,
Isn't it related to Uvicorn? How can SQLAdmin decide that?

https://aminalaee.dev/sqladmin/faq/
https://www.uvicorn.org/deployment/#running-behind-nginx

**Comment by aminalaee** [comment]
@jsmolina Any updates?
