### ISSUE TITLE
Add milestones 

### ISSUE THREAD

**Issue by HiperMaximus** [aminalaee/sqladmin#315]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

It would be neat to see the roadmap of the project and feature parity with Flask Admin

### Describe the solution you would like.

Adding milestones and issues that list the features that are being implemented/are planned and that are easy to check

**Comment by aminalaee** [comment]
Thanks for the suggestion, yeah makes sense. I'll do that.

**Comment by aminalaee** [comment]
This is a great idea, I've started the feature parity in #316 and I'll keep working on the milestones. Thanks for the suggestion.
