### ISSUE TITLE
Error when searching for uuid

### ISSUE THREAD

**Issue by junoriosity** [aminalaee/sqladmin#363]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I am trying to search for a UUID, but I get a bug then, namely

```
api-web-1  |     value = _python_UUID(value)
api-web-1  |   File "/usr/local/lib/python3.10/uuid.py", line 177, in __init__
api-web-1  |     raise ValueError('badly formed hexadecimal UUID string')
api-web-1  | sqlalchemy.exc.StatementError: (builtins.ValueError) badly formed hexadecimal UUID string
```

Do you know how to fix it? It works nicely with string, however, but simply not for UUID.

### Steps to reproduce the bug

```
class Group(SQLModel, table=True):
    group_id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True, index=True, nullable=False)

class GroupAdmin(ModelView, model=Group):
    column_list = [Group.group_id]
    column_searchable_list = [Group.group_id]

admin = Admin(app, engine)

admin.add_view(GroupAdmin)
```

### Environment

- MacOS
- Python 3.10
- SQLAdmin 0.6.1

**Comment by junoriosity** [comment]
@aminalaee Could you explain to me how I could use it then?

**Comment by aminalaee** [comment]
I will try to release this tomorrow so you can install version `0.7.0` to use it.
