### ISSUE TITLE
Cannot edit item

### ISSUE THREAD

**Issue by junoriosity** [aminalaee/sqladmin#364]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I would like to edit in my database, yet when I click on the edit button I get an `Internal Server Error` with the following server error message

```
...
api-web-1  |   File "/usr/local/lib/python3.10/site-packages/sqladmin/helpers.py", line 118, in get_primary_key
api-web-1  |     assert len(pks) == 1, "Multiple Primary Keys not supported."
api-web-1  | AssertionError: Multiple Primary Keys not supported.
```

Do you know how to fix it?

### Steps to reproduce the bug

```
class User(SQLModel, table=True):
    user_id: str = Field(primary_key=True, nullable=False)
    e_mail: EmailStr

class UserAdmin(ModelView, model=User):
    column_list = [User.user_id]
    column_searchable_list = [User.user_id]

admin = Admin(app, engine)

admin.add_view(UserAdmin)
```

### Environment

- MacOS
- Python 3.10
- SQLAdmin 0.6.1

**Comment by su-shubham** [comment]
> #63  
No multiple PK support.

**Comment by junoriosity** [comment]
@su-shubham Many thanks for getting back to me. The strange thing is, however, that I do have just one primary key.

**Comment by su-shubham** [comment]
@junoriosity  It works fine if you have one primary key but multiple keys still not supported in sql admin.

**Comment by aminalaee** [comment]
Thank you both, as you can see here the line: https://github.com/aminalaee/sqladmin/blob/fac20e1aa1bd0be7b770ee69c8676d43ea739817/sqladmin/helpers.py#L118 this is coming from SQLAlchemy inspection, so your model should definitely have multiple PKs or that SQLAlchemy is somehow confused about your model.
In any case I don't think there's much to be done here.

**Comment by su-shubham** [comment]
@aminalaee Can I achieve it if  I have composite key in one model.

**Comment by aminalaee** [comment]
TBH I have not tried it but I think it should work. Depends on how SQLAlchemy would inspect that.

**Comment by aminalaee** [comment]
Closing it due to inactivity.
