### ISSUE TITLE
Starlite integration

### ISSUE THREAD

**Issue by cofin** [aminalaee/sqladmin#384]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

I'd like to be able to use this with the Starlite framework.

### Describe the solution you would like.

Starlite recently removed the Starlette dependency, limiting the ability to use this tool on that framework.  I would like to contribute to a solution that works with Starlite.

I'm looking for guidance on how best to integrate this functionality. (i.e. separate fork, PR to integrate into main)

**Comment by aminalaee** [comment]
Hi,

thanks for the suggestion. Yeah I think it would be valuable to add it. I just need to take a look or maybe give it a try to see how much work is needed.

Feel free to do the same, I know you have far batter knowledge of Starlite than me.
