### ISSUE TITLE
Allow different views for same model

### ISSUE THREAD

**Issue by jsmolina** [aminalaee/sqladmin#391]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Identity is not overwritten in metaclass even if in attrs
`cls.identity = slugify_class_name(model.__name__)` 

### Describe the solution you would like.

It should be possible to create something like
`cls.identity = attrs.get("identity", slugify_class_name(model.__name__)`

Although edit links will need to be updated accordingly, of course.

**Comment by aminalaee** [comment]
Hi,
yeah, even though I didn't plan to introduce this as a public API, I see this is already crept into the docs. This is an easy fix, feel free to do it, otherwise I will do it later.

**Comment by jsmolina** [comment]
> Hi, yeah, even though I didn't plan to introduce this as a public API, I see this is already crept into the docs. This is an easy fix, feel free to do it, otherwise I will do it later.

I tried but I had some issues when trying to click on edit one of the rows, as it tried to use the normal identity of the table.
I could try to do you a PR but it will take some days to get some spare time.

**Comment by aminalaee** [comment]
Hey, can you clarify the use-case you have? I've been looking into this and there's a limitation:

In list page, if there's a relationship, we actually link the related model so let's say you are viewing list of Users and you click their Organization's name in list, then you are redirected to the Organization detail.

But with this approach we can't find which view to redirect as there are two views registered for this Model.

**Comment by jsmolina** [comment]
well it's just having the same model but listing the users by role, let's say: 

- user roles
- administrator roles
Sorry for the late reply.

**Comment by aminalaee** [comment]
I think you're better off writing a custom view.
