### ISSUE TITLE
Add screenshots on the README

### ISSUE THREAD

**Issue by Kludex** [aminalaee/sqladmin#395]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

No problem...

### Describe the solution you would like.

I shared this package with a friend, and he said: "some screenshots on the README would be great...".

Just sharing his feedback here... :eyes:

**Comment by aminalaee** [comment]
Hey, @Kludex 

Thanks for the feedback. Yeah you're right, I'll add them.

By the way you can check the online demo too.

**Comment by aminalaee** [comment]
I added them, thank you 👍

**Comment by Kludex** [comment]
Thank you :pray:
