### ISSUE TITLE
Support SQLAlchemy v2

### ISSUE THREAD

**Issue by odigity** [aminalaee/sqladmin#410]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

A few days ago I started using SQLAlchemy for the first time - specifically, v2.0.0rc2 (released 2023-Jan-9).  Today I decided to try setting up an admin UI, and after determining the Flask-Admin is broken and unmaintained, I decided to try `sqladmin` - but couldn't install it because your `pyproject.toml` specifies version `<1.5`.

### Describe the solution you would like.

Given that SQLAlchemy v2 is expected to come out in the next few weeks, now seems like the time to make sure sqladmin works with it, and then loosen the version specifier.

### Describe alternatives you considered

I don't see an alternative.  I want to stay with SQLAlchemy v2, and sqladmin directly interacts with the models, so the backend and admin have to at least share the model code, which means they might as well be in the same project - which means they have to share the same list of package dependencies.

**Comment by aminalaee** [comment]
Hey, thanks for this.

Yes that is very reasonable and I will give it a try.
As far as I know there should be no problems as SQLAlchemy 1.4 and 2.0 will not be much different, I will give it a try and update this.

**Comment by aminalaee** [comment]
I created the draft PR for now to wait until V2 is released.

**Comment by odigity** [comment]
https://sqlalchemy.org/blog/#sqlalchemy-2.0.0-released
