### ISSUE TITLE
SQLAlchemy 2.0 Related models are displayed incorrectly

### ISSUE THREAD

**Issue by Neykuratick** [aminalaee/sqladmin#432]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

<img width="1192" alt="Screenshot 2023-02-18 at 10 36 11" src="https://user-images.githubusercontent.com/63598014/219848076-468e0918-d1a9-4388-b5a3-3b3d20d389fb.png">

### Steps to reproduce the bug

I have two models and admin class:

First model:
```
class DomainModel(TimeMixin, Base):
    __tablename = "domains"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    name = Column(String, unique=True)
    owner_id: int = Column(ForeignKey('users.id', ondelete="CASCADE"), nullable=False)
    owner: Mapped[UserModel] = relationship("UserModel", lazy="joined")
```

Second model:
```
class UserModel(TimeMixin, Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    username = Column(String, unique=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)
```

And the admin class:

```
class ModelAdmin(ModelView, model=DomainModel):
    column_list = [DomainModel.id, DomainModel.name]
```

ModelView defined as is:

```
from sqladmin import ModelView as BaseModelView


class ModelView(BaseModelView):
    save_as = True
    form_widget_args = dict(created_at=dict(readonly=True))
```

### Expected behavior

UserModel displayed in the admin panel as dict or as some of its column attribute

### Actual behavior

UserModel displayed as a memory address

### Environment

SQLAlchemy 2.0.4
sqladmin 0.9.0
FastAPI 0.92.0

### Additional context

I've read almost all the issues, but most of them are either SQLModel related or don't mention the problem I have. Things I've tried:

Using mapped column:

```
class DomainModel(TimeMixin, Base):
    __tablename = "domains"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    name = Column(String, unique=True)
    owner_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    owner: Mapped["UserModel"] = relationship(lazy='joined')
```

Configuring model view:

```
class ModelAdmin(ModelView, model=DomainModel):
    column_list = [DomainModel.id, DomainModel.name]
    column_formatters_detail = {UserModel: lambda m: m.name}
```

**Comment by Neykuratick** [comment]
Found a workaround with just modifying string representation of the related model:

```
class UserModel(TimeMixin, Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    username = Column(String, unique=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)

    def __str__(self):
        return self.username
```

<img width="1188" alt="Screenshot 2023-02-18 at 10 56 21" src="https://user-images.githubusercontent.com/63598014/219848891-34eba51b-e931-4804-8583-25ef877b7463.png">

**Comment by aminalaee** [comment]
@Neykuratick Glad you solved it.
Just an FYI this is not only for V2 models, any object would be the same.
