### ISSUE TITLE
Support OAuth integration in AuthenticationBackend

### ISSUE THREAD

**Issue by aminalaee** [aminalaee/sqladmin#442]
### Discussed in https://github.com/aminalaee/sqladmin/discussions/439

<div type='discussions-op-text'>

<sup>Originally posted by **simonsax** March  3, 2023</sup>
I have a simple fastapi app with the sqladmin backend for which I'd like to enable a SSO login functionality. But somehow I'm unable to redirect to the authentication_url of my OIDC provider. I'm using authlib as oauth client

From my understanding when accessing /admin the `authenticate` function is run. In this function I would check for a token or the session and if the user is not logged in yet, I would call the login endpoint (which redirects to the auth_url of my OICD provider) or call the OICD authentication method directly. But somehow I'm not redirected to the corresponding url, probably because the function expects a boolean return value? Any idea how to solve that problem? Otherwise this could be a cool feature :-)

If I call the `/sso_login` endpoint directly auth flow works fine.

Thanks a lot for your valuable inputs.

```
...
class MyBackend(AuthenticationBackend) -> bool::
    async def login(self, request: Request):
        #not used as it is only used for the admin form (which I try not to use -> SSO instead)
        pass

    async def logout(self, request: Request) -> bool:
        # Usually you'd want to just clear the session
        request.session.clear()
        return True

    async def authenticate(self, request: Request) -> bool::
        token = request.session.get("token")
        if not token:
            redirect_uri = request.url_for('sso_login')
            return RedirectResponse(url="/sso_login")
            #return await oauth.OIDC.authorize_redirect(request, redirect_uri) -> 2nd Option: call auth_url direclty
            #return False -> according to doc boolean return value
        # token = await oauth.OIDC.authorize_access_token(request)
        # Check the token -> e.g. oauth.OIDC.authorize_access_token(request)
        return True

#add sqladmin to app
admin_backend = Admin(app=app,engine=engine, authentication_backend=MyBackend("dfkdvdfsd"))

@app.get('/sso_login')
async def sso_login(request: Request):
    redirect_uri = request.url_for('auth_callback')
    return await oauth.OIDC.authorize_redirect(request, redirect_uri)
```</div>

**Comment by simonsax** [comment]
just added a comment to the PR: https://github.com/aminalaee/sqladmin/pull/440

**Comment by aminalaee** [comment]
Hey @simonsax .
Did you install the latest code from git? Because the latest change for auth backend is not released yet.

**Comment by simonsax** [comment]
of course NOT -.-. It works like a charm. Thx a lot and sorry!

**Comment by aminalaee** [comment]
Glad it is resolved.
