### ISSUE TITLE
how to use ChoiceType?

### ISSUE THREAD

**Issue by xuehaoweng** [aminalaee/sqladmin#478]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

sqladmin.exceptions.NoConverterFound: Could not find field converter for column symbol (<class 'sqlalchemy_utils.types.choice.ChoiceType'>)

my code like this :
condition_choices = [(0, '='), (1, '/='), (2, '>'), (3, 'include'), ]
symbol = Column(ChoiceType(condition_choices, Integer()), default=0)

but  when i use sqladmin , i got this error "sqladmin.exceptions.NoConverterFound: Could not find field converter for column symbol (<class 'sqlalchemy_utils.types.choice.ChoiceType'>)"

### Steps to reproduce the bug

sqladmin.exceptions.NoConverterFound: Could not find field converter for column symbol (<class 'sqlalchemy_utils.types.choice.ChoiceType'>)

my code like this :
condition_choices = [(0, '='), (1, '/='), (2, '>'), (3, 'include'), ]
symbol = Column(ChoiceType(condition_choices, Integer()), default=0)

but  when i use sqladmin , i got this error "sqladmin.exceptions.NoConverterFound: Could not find field converter for column symbol (<class 'sqlalchemy_utils.types.choice.ChoiceType'>)"

### Environment

windows/python3.8/sqladmin0.10.3

**Comment by aminalaee** [comment]
Hey, this is not supported yet.
Feel free to implement it here: https://github.com/aminalaee/sqladmin/blob/main/sqladmin/forms.py#L468
Otherwise I will get it when I have the capacity.

**Comment by xuehaoweng** [comment]
Thank you for your reply!
