### ISSUE TITLE
PostgreSQL: Could not find field converter for column with INTERVAL type

### ISSUE THREAD

**Issue by anton-petrov** [aminalaee/sqladmin#485]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When trying to edit entity with interval field, getting such an error:
```
sqladmin.exceptions.NoConverterFound: Could not find field converter for column update_interval (<class 'sqlalchemy.dialects.postgresql.base.INTERVAL'>)
```

### Steps to reproduce the bug

Database: PostgreSQL 14.

Add new field with interval type, for example:
```python
from sqlalchemy.dialects.postgresql import INTERVAL
from sqlalchemy.orm import declarative_base

Base = declarative_base()
metadata = Base.metadata

class Devices(Base):
    __tablename__ = "Devices"
...
    update_interval = Column(
        INTERVAL,
        server_default=text("make_interval(0, 0, 0, 0, 0, 5, (0)::double precision)"),
        comment="Some frequency",
    )
```

### Expected behavior

Can edit interval field

### Actual behavior

Internal Server Error

```
File "/usr/local/lib/python3.11/site-packages/sqladmin/forms.py", line 266, in get_converter
 raise NoConverterFound(  # pragma: nocover
sqladmin.exceptions.NoConverterFound: Could not find field converter for column update_interval (<class 'sqlalchemy.dialects.postgresql.base.INTERVAL'>).
```

### Environment

Ubuntu 22.04, CPython 3.11.3

**Comment by aminalaee** [comment]
Hi,

Right now we only support SQLAlchemy Interval type not Postgresql's INTERVAL type.
Not sure how much they are different, but this Postgres specific one can be added here: https://github.com/aminalaee/sqladmin/blob/main/sqladmin/forms.py#L427

Feel free to create a PR for it.

**Comment by anton-petrov** [comment]
Just changed column type from Postgresql's interval type to SQLAlchemy and it works!
Thank's for answer and no need for the new PR.
