### ISSUE TITLE
Https redirect

### ISSUE THREAD

**Issue by AdnanAvdagic** [aminalaee/sqladmin#487]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I have a HTTPS redirect middleware working for my FASTAPI setup but for SQLAdmin it does not work since SQLAdmin is constantly trying to load its pages over http which makes the server just redirect back and forth between http and https.

Running without HTTPS Middleware makes it not load since some content is loaded over http and some over https and we have HSTS running so all content must be served over https

### Steps to reproduce the bug

` admin_middlewares = [Middleware(HTTPSRedirectMiddleware)]
    admin = Admin(
        app,
        engine=engine,
        authentication_backend=authentication_backend,
        templates_dir="app/admin/templates",
        middlewares=admin_middlewares,
    )`

### Expected behavior

I expect SQLadmin to load over https and stay that way

### Actual behavior

it tries loading http which just loads https in a loop

### Environment

- Docker running Ubuntu 22.04
- Python 3.11
- SQLAdmin 0.10.3
- FastAPI 0.92.0

**Comment by AdnanAvdagic** [comment]
Made it work with gunicorn proxy-pass, apparently it was needed even if I'm not behind nginx etc. becauce of starlette not seeing the https scheme and then running on http instead in request.url_for

**Comment by sternalon** [comment]
HI, I am having a similar problem. Could you please provide additional details about your solution or further insights about the problem. Thanks

**Comment by just-an-dev** [comment]
For example if you use uvicorn you can set proxy_headers and forwarded_allow_ips to ba able to generate https link

`
uvicorn.run(app, host="0.0.0.0", port=8080, proxy_headers=True, forwarded_allow_ips="*")
`

**Comment by mpizosdim** [comment]
I still cant manage to solve when using nginx.
None of the above worked.

**Comment by aminalaee** [comment]
Check this out https://aminalaee.dev/sqladmin/cookbook/deployment_with_https/
