### ISSUE TITLE
Cannot sort by Foreign Key

### ISSUE THREAD

**Issue by patrykko-intel** [aminalaee/sqladmin#489]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When I'm trying to sort a table using foreign key value, I got an error. My question is: is it even possible?

Error I have:
sqlalchemy.exc.CompileError: Can't resolve label reference for ORDER BY / GROUP BY / DISTINCT etc. Textual SQL expression 'foreign_key_name' should be explicitly declared as text('foreign_key_name')

Configuration   
column_sortable_list = [Host.key, Host.foreign_key_name, Host.description]

### Steps to reproduce the bug

Create a model with foreign key, and add it to the column_sortable_list.

### Expected behavior

Sort properly.

### Actual behavior

Raises an error.

### Environment

- Python 3.10
- Sqlaadmin 0.10.3
-  FastAPI 0.92.0

**Comment by aminalaee** [comment]
Hi,
Yes it is possible, can you please provide a minimal example of your model and ModelAdmin setup so I can reproduce this?

**Comment by patrykko-intel** [comment]
Of course:

class Host(Base):

    id = Column(Integer, primary_key=True)

    key = Column(Text, nullable=False, unique=True)

    fk1_id = Column(ForeignKey(Fk1.id))
    fk1= relationship("Fk1")
    fk1_alias = aliased(Fk1)

 
    mode = Column(Text, nullable=False)

    description = Column(Text)

class Fk1(Base):
    id = Column(Integer, primary_key=True)

    key = Column(Text, nullable=False, unique=True)

    local_location = Column(Text, nullable=False)
    remote_location = Column(Text)
    ipxe_script_name = Column(Text, nullable=False)
    special_purpose = Column(Text)
    special_active = Column(Boolean)


class HostAdmin(ModelAdmin, model=Host):
    column_list = [
        Host.key,
        Host.fk1,
    ]
    form_columns = [
        Host.key,
        Host.fk1,
    ]
    column_sortable_list = [Host.key, Host.fk1, Host.description]
    column_searchable_list = [Host.key, Host.fk1, Host.description]

**Comment by patrykko-intel** [comment]
Is it possible for you to provide me an example how in your case sorting by foreign key works?

**Comment by aminalaee** [comment]
In your example `Host.fk1` is not a ForeignKey, it's a Relationship attribute.
What I meant by foreign key is that sorting by `Host.fk1_id` will work, but not sure how sorting by a relationship should work.

**Comment by aminalaee** [comment]
Any update @patrykko-intel ?
