### ISSUE TITLE
Admin As Boilerplate

### ISSUE THREAD

**Issue by ManiMozaffar** [aminalaee/sqladmin#494]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Hey,
The principal of FastAPI is to be SOLID, however I found this repo as not following SOLID.
The SQLAdmin is aware of framework and database, however it shouldn't be. 
So how about shifting this project to a Boilerplate? or maybe as another repo? where you can clone it, and take benefit of the written code as a template?

Currently I'm doing something similar, after I found out that what i'm doing as well isn't solid and a good practice.

### Describe the solution you would like.

generate a Boilerplate or template

### Describe alternatives you considered

I don't see any

**Comment by aminalaee** [comment]
Hey,
I think my idea was to solve only one problem and I wanted to limit the framework and database.
Anyway I think it's a good suggestion, so what exactly do you think I can do?

**Comment by ManiMozaffar** [comment]
> I think my idea was to solve only one problem and I wanted to limit the framework and database.

but this isn't SOLID :(
we use FastAPI to have best experience of SOLID pattern design. 
What you did was great job, but it's about how you represent it!
I was actually doing something you did until yesterday, to limit framework and database to make integration with fastapi "faster"
but we have a saying:
> The only way to go fast is to go well.

so I took a look at this Boilerplate,
https://github.com/iam-abbas/FastAPI-Production-Boilerplate
and I was like "hmm, how about I write my library as Boilerplate template? with adding what I want?"
Boilerplate template gives you well-deserved and well-structured speed ;) Even seb himself wrote some boilerplates.
maybe that's something you can do, as another repo, or maybe with me, just take it as offer :)

btw it appears that you're Iranian, would be great if we can have you in our community!

**Comment by aminalaee** [comment]
Yeah, I'm open to improve this project, so any suggestion or contributions are welcome.

And about setting up a new project, I have some ideas for a refactor or a separate project based on this one, if you are interested we can talk through email so we can include your ideas in that.

> btw it appears that you're Iranian, would be great if we can have you in our community!

Yes, I am and sure, I'll be honoured :)
