### ISSUE TITLE
View all columns 

### ISSUE THREAD

**Issue by maurosaladino** [aminalaee/sqladmin#495]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Is there a configuration to display all columns of a table? Currently, I am using the following piece of code:

```
class ModelAdmin(ModelView, model=Model):
    column_list = [c_attr.key for c_attr in Model.__mapper__.column_attrs]
```

### Describe the solution you would like.

It would be nice to set a configuration optional like `show_all_columns=True` (or something like that) to display all columns:

```
class ModelAdmin(ModelView, model=Model):
    show_all_columns = True
```

Thank you!

**Comment by aminalaee** [comment]
Hi,
Sounds like a reasonable request. Maybe something like Django Rest Framework `__all__` special tag for example:


```py
class ModelAdmin(ModelView, model=Model):
    column_list = '__all__'
```

**Comment by maurosaladino** [comment]
> Hi, Sounds like a reasonable request. Maybe something like Django Rest Framework `__all__` special tag for example:
> 
> ```python
> class ModelAdmin(ModelView, model=Model):
>     column_list = '__all__'
> ```

Sounds great!
