### ISSUE TITLE
Multi PK key for sqladmin

### ISSUE THREAD

**Issue by DanyaKrats** [aminalaee/sqladmin#496]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

We need to inherit and change the logic in the sqladmin models to be able to add tables with multi PKs.
If unsolvable restrictions are found for this task, then it will be necessary to add constraints to the tables where multi PKs are needed (for example "user_claims")

**Comment by aminalaee** [comment]
Hi,
There's already an open issue for this https://github.com/aminalaee/sqladmin/issues/63

Feel free to start working on it and contribute to the project, but AFAIK there will be limitations and only some features will work with multi PK models.
