### ISSUE TITLE
Use relative URLs instead of absolute URLs

### ISSUE THREAD

**Issue by allentv** [aminalaee/sqladmin#497]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

When I try out the package without HTTPS, all URLs work including static assets but when I turn on HTTPS, there are issues with mixed content as an absolute URL is generated for all assets instead of relative URLs. This is stopping me from using this package in PROD deployments where HTTPS is mandatory.

### Describe the solution you would like.

All URLs are relative to the admin URL

**Comment by aminalaee** [comment]
Hey,
Have you checked this page?
https://aminalaee.dev/sqladmin/faq/

There's an online demo running with HTTPS so probably something wrong with how you deploy it.

**Comment by silver8ack** [comment]
> Hey, Have you checked this page? https://aminalaee.dev/sqladmin/faq/
> 
> There's an online demo running with HTTPS so probably something wrong with how you deploy it.
Do you have an example of how it was deployed?  I can't seem to get any of the static files served in Openshift or behind Nginx.  I'm getting 'mixed content' errors when using openshift Ingress.  The --proxy-headers doesn't do anything.

**Comment by tariqjamal057** [comment]
@aminalaee, I had configured the package with application correctly in http it working file but in production it showing the below error

> Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS.
