### ISSUE TITLE
Support for @login_required decorator in custom views

### ISSUE THREAD

**Issue by MaximZemskov** [aminalaee/sqladmin#512]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Hey,

Right now, we can't use @login_required in custom views and need to manually handle authentication, which is a bit of a hassle.

Think it'd be cool to allow @login_required with custom views. It would make things easier and more readable.

**Comment by aminalaee** [comment]
Hey, yeah that makes sense, It's a simple fix.
