### ISSUE TITLE
Access request context for database queries

### ISSUE THREAD

**Issue by rossmacarthur** [aminalaee/sqladmin#540]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

All of my models have a `created_at_by_user_uid` and `updated_at_by_user_uid` column. I want to be able to automatically set these fields based on the authenticated user. The authenticated user is available on the `Request` but the request is not available to the database queries since:
- the database connection is provided globally not at request context level
- there is no way to inject field values based on the request context

### Describe the solution you would like.

I think there are various ways to solve this, here are some options
- Pass `Request` to `on_model_change` and friends
- at the query level, `delete_model`, `insert_model`, `update_model` could be passed the `Request` model
- do it in the model view by passing `Request` to functions like `get_object_for_edit`, `get_object_for_details`
- at the db session level: e.g. allowing the construction of a custom database session based on the request

### Describe alternatives you considered

- I'm currently doing it at the form level by overriding `_handle_form_data` which is very gross and it has some limitations, I have to check if it is a "create" or "update" by looking at the path.
- I considered overriding all of the route handlers but they're quite large.

**Comment by aminalaee** [comment]
Hey, thanks for the clear explanation and suggestions.
I think using the events like `on_model_change` will be the the easiest for this case.

Even though I think having the `request` in `get_object_for_details` and `list` is also useful for object-level permissions per User, we can deal with this separately.

Feel free to create a PR with this approach, or I can do it whenever I get the chance.

**Comment by rossmacarthur** [comment]
Hi @aminalaee,

The one problem is that `on_model_change` is called inside the `Query` object. So to get the request object there we would have to pass it through quite a few functions. All of the following method signatures would change to take the request object:

- `BaseView.delete_model`
- `BaseView.update_model`
- `BaseView.insert_model`
- `Query.delete`
- `Query.update`
- `Query.insert`
- `BaseView.on_model_change`

Possibly then the following as well
- `BaseView.after_model_change`
- `BaseView.on_model_delete`? (for consistency maybe)
- `BaseView.after_model_delete`? (for consistency maybe)

I'm happy to make this change but just want to check that it is fine to change the signature of all of these functions.

For my purposes it is sufficient to just pass it to the `delete_model`, `update_model`, and `insert_model`.  Example in my fork: https://github.com/rossmacarthur/sqladmin/commit/f0ee41ee988b6a6b5dfb3c9ba673b31af0703a17

**Comment by aminalaee** [comment]
I have checked how it's done in more mature projects like Flask and Django.
So Flask obviously has a different context and you could just import `from flask import request` and that would be easy.
The design is different in Starlette/FastAPI and more like Django we have to pass the request object around.

But I also agree that let's start with the minimal approach to do this and keep improving it.
Initially I thought `on_model_change` would have the least amount of change, but I think I was wrong. Changing these is more straightforward:

```py
- delete_model
- insert_model
- update_model
```
These are called directly from the the Starlette application where the `request` is available.
And the final code should look something like:

```py
class UserAdmin(ModelAdmin, model=User):
    async def insert_model(data, request):
        data["user"] = request.user
        return await Query(self).insert(data)
```

What do you think?
