### ISSUE TITLE
Support multiple databases

### ISSUE THREAD

**Issue by meetinger** [aminalaee/sqladmin#559]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Sometimes we need multiple databases for a project, 
but in this application I haven't found how to do that.

### Describe the solution you would like.

One possible solution could be to pass the sessionmaker factory instead of the engine.
SQLAlchemy documentation page about routing:
https://docs.sqlalchemy.org/en/20/orm/persistence_techniques.html#session-partitioning

### Describe alternatives you considered

Multiple instance of Admin()???

### Additional context

I found a PR with sessionmaker:
https://github.com/aminalaee/sqladmin/pull/542

**Comment by hsiaoer** [comment]
Hello - thanks in advance for an awesome open sourced repo! I'm also interested in how we can support a connection to multiple databases. On thing I've tried is to have multiple `Admin` view associated with a single FastAPI app.

```
admins = [
    Admin(app, create_engine(database_dsn), base_url=f"/{customer_name}", title=customer_name)
    for customer_name, database_dsn in multiple_databases
]
for admin in admins:
    admin.add_view(MyView)
```

This builds correctly but when we then dig into each admin app, the links point to the wrong Admin app for the customer. For example, if I'm looking at models for customer B (`url=mysite.com/customer-b`), all the links in the app will point to customer A (`url=mysite.com/customer-a/item`). I've traced the issue to to this spot https://github.com/aminalaee/sqladmin/blob/main/sqladmin/application.py#L406 where we are mounting the app.

Happy to contribute to solve for the multi-database use case but wanted to see if anyone had any ideas
