### ISSUE TITLE
SQLModel support

### ISSUE THREAD

**Issue by aminalaee** [aminalaee/sqladmin#57]
### Discussed in https://github.com/aminalaee/sqladmin/discussions/56

<div type='discussions-op-text'>

<sup>Originally posted by **JonasKs** February 16, 2022</sup>
Hi! This looks awesome, I’m definitely going to test it out! 

Since this support SQLAlchemy, will it also support SQLModel? 😊</div>

As suggested by @JonasKs, I did test SQLAdmin with SQLModel but it needs a few tweaks to make it work.
I'll get to it after we have the minimum functionality like #24 done.

**Comment by aminalaee** [comment]
Thanks a lot for the suggestion 👍

**Comment by ischaojie** [comment]
Awesome! `SQLModel` use `pydantic` for type annotation, that is better for model convert to forms, for example, 

```python
name: str = Field(max_length=12)
age: int = Field(ge=0, le=100)
```
We can auto-add validators for `name` and `age` fields in wtforms Forms.

If needed, I wish to provide some contribution to it.

**Comment by aminalaee** [comment]
Honestly I haven't taken a deep look into it, but yeah maybe something like that will do it.

What I suggest is to split that into multiple PRs, so my first attempt would be to just make it work with SQLModel because right now the field conversion fails.
Then we. can work on it and improve the validations.
Even in that, if any PR will be big we can split it into parts. 

> If needed, I wish to provide some contribution to it.

That would be more than welcome, feel free to go for it 👍

**Comment by EZhivaikin** [comment]
Sounds great, I'll try to do this all asap 😃
