### ISSUE TITLE
WYSIWYG editor for TextField

### ISSUE THREAD

**Issue by i3Cheese** [aminalaee/sqladmin#571]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

I want to add a WYSIWYG editor to my text fields. Something like CKEditor. 

Is there any way I can do it?
Maybe someone has already done something similar.

**Comment by aminalaee** [comment]
Hey @i3Cheese ,

As far as I have checked you need to inject custom JS code to make this possible, previously it would work with just assigning `ckeditor` CSS class to the HTML field, but now I don't see that works.

Based on that the following works for me:

- Create a templates directory in your project
- Add this `custom_edit.html` file there:
```html
{% extends "edit.html" %}
{% block tail %}
<script src="https://cdn.ckeditor.com/ckeditor5/39.0.1/classic/ckeditor.js"></script>
<script>
    ClassicEditor
        .create(document.querySelector('#name'))  // Or any other field
        .catch(error => {
            console.error(error);
        });
</script>
{% endblock %}
```

- Specify this in your admin:
```py
class UserAdmin(ModelView, model=User):
    edit_template = "custom_edit.html"
```

I know some pieces were missing from the docs, I'm working on a PR to add this.

**Comment by i3Cheese** [comment]
Thank you!
