### ISSUE TITLE
add horizontal scroll bar to the list view

### ISSUE THREAD

**Issue by aminalaee** [aminalaee/sqladmin#580]
Is it possible to add horizontal scroll bar to the list view?

_Originally posted by @anton-petrov in https://github.com/aminalaee/sqladmin/discussions/579_

**Comment by anton-petrov** [comment]
When I updated tabler to the newest version, horizontal bar appeared :)

**Comment by aminalaee** [comment]
Cool, I will update the tabler version now.

**Comment by aminalaee** [comment]
Updating Tabler only works fine for me. I will create a PR so we can check this out.

**Comment by anton-petrov** [comment]
What files did you updated?

**Comment by anton-petrov** [comment]
This issue can be closed now.
