### ISSUE TITLE
issue with Admin session_maker type hint

### ISSUE THREAD

**Issue by sheldygg** [aminalaee/sqladmin#603]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

![image](https://github.com/aminalaee/sqladmin/assets/85823514/1215a1b0-a232-4b8c-be0d-d406444c9dbd)

### Environment

last version of sqladmin

**Comment by aminalaee** [comment]
Which version of sqlalchemy are you using? V2 I think?

**Comment by sheldygg** [comment]
> Which version of sqlalchemy are you using? V2 I think?

latest from pypi

**Comment by sheldygg** [comment]
?
