### ISSUE TITLE
Bulk delete shows no confirmation prompt

### ISSUE THREAD

**Issue by sorix6** [aminalaee/sqladmin#608]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When deleting an item one by one, a popup asking for confirmation is shown. This is not the case with bulk delete, where the action is performed immediately.
It also does not seem possible to disable bulk delete while keeping the ability to delete one by one.

### Environment

MacOS/Python3.11/SQLAdmin0.14.1

**Comment by aminalaee** [comment]
Thanks for reporting this.
As far as I can tell this was never implemented. Do you have any cases like Django admin has this behaviour?

**Comment by sorix6** [comment]
Hi, I have looked into Django admin and it does require confirmation before bulk delete. According to their [documentation](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/actions/#actions-that-provide-intermediate-pages)  ` the built-in delete action asks for confirmation before deleting the selected objects.`
