### ISSUE TITLE
Customized sort_query

### ISSUE THREAD

**Issue by YarLikviD** [aminalaee/sqladmin#624]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

At the moment, the admin panel does not support sorting by objects, but this can be solved using the custom sort_query method. Similar to list_query, search_query.

### Describe the solution you would like.

You can move the sorting from the main list method to separate methods.
``` Python
    async def list(self, request: Request) -> Pagination:
        ...
        sort_fields = self._get_sort_fields(request)
        stmt = self.sort_query(stmt, sort_fields)
        ...      
```
A separate method for getting fields.
```Python 
    def _get_sort_fields(self, request: Request) -> List[Tuple[str, bool]]:
        sort_by = request.query_params.get("sortBy", None)
        sort = request.query_params.get("sort", "asc")

        if sort_by:
            sort_fields = [(sort_by, sort == "desc")]
        else:
            sort_fields = self._get_default_sort()

        return sort_fields
```
And an overridable method that can be used at your discretion. 
```Python
    def sort_query(self, stmt: Select, sort_fields: List[Tuple[str, bool]]) -> Select:
        for sort_field, is_desc in sort_fields:
            if is_desc:
                stmt = stmt.order_by(desc(sort_field))
            else:
                stmt = stmt.order_by(asc(sort_field))

        return stmt
```
The idea of custom methods solves many problems and gives great flexibility.
I haven't actually added anything, but it solves the problem with sorting by object.

**Comment by aminalaee** [comment]
I think that's a good idea, I think even passing `request` instead of `sort_fields` makes sense maybe they can customize it more.

So:

```py
def sort_query(self, stmt: Select, request: Request) -> Select:
        for sort_field, is_desc in sort_fields:
            if is_desc:
                stmt = stmt.order_by(desc(sort_field))
            else:
                stmt = stmt.order_by(asc(sort_field))

        return stmt
```

PRs are welcome.
