### ISSUE TITLE
overide delete_model method

### ISSUE THREAD

**Issue by spark-19977** [aminalaee/sqladmin#650]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

problem that sqladmin doesn't correct delete related models with ondelete=cascade

### Describe the solution you would like.

solution is override delete_model method from:
await session.delete(obj)
to:
await session.execute(delete(self.model).filter_by(id=pk))

**Comment by aminalaee** [comment]
@spark-19977 Can you provide a minimal example to reproduce this?
It seems to be working fine and also the solution you have mentioned doesn't work we are not using `session.delete(obj)` at all.
