### ISSUE TITLE
Sort sidepanel

### ISSUE THREAD

**Issue by holdmybeer1min** [aminalaee/sqladmin#662]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

After every restart sidepanel has models in different order

### Describe the solution you would like.

Simple alphabetical sort would do. 

### Additional context

I'll debug it at some point and see if a simple flag in template can fix it but I'm leaving this here as well in case someone else wants to give it a shot

**Comment by aminalaee** [comment]
Using the latest version should solve this issue. Which version are you using?
