### ISSUE TITLE
on_form_prefill functionality

### ISSUE THREAD

**Issue by JettScythe** [aminalaee/sqladmin#680]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

I want to be able to have a field depend on another field and have it populate with a certain value when selected. 
flask-admin has this for [editing](https://flask-admin.readthedocs.io/en/latest/_modules/flask_admin/model/base/#BaseModelView.on_form_prefil), I would like it for creating. 

### Describe the solution you would like.

As an example, I have a custom form: 
```
class ToolForm(Form):
    name = SelectField("Name", choices=[(tool_name, tool_name) for tool_name in KnownTools.get_all_tool_names()])
    config = JSONField("Config", validators=[InputRequired()])
```

When a user selects a name in the admin panel, I want to prefill the config field with the associated tool schema. In the case of a tool to send emails, you can imagine the config template to look something like
```
class SendEmailConfig(BaseModel):
    sending_address: str
    mail_server: str
    mail_server_port: int
    mail_username: str
    mail_password: str
```

So, when a user selects "send_email" from the name dropdown, I would like the config field to default to 
```
{
    "sending_address": "str"
    "mail_server": "str"
    "mail_server_port": int
    "mail_username": "str"
    "mail_password": "str"
}
```

I think it would be nice to have an on_form_change method like on model_change
Assuming data is the form, I would like to be able to do something like:
```
async def on_form_change(self, data: Form, is_created: bool, request: Request):
    if is_created:
        default_config_class = KnownTools.get_tool(data.name).config
        data.config = json.dumps({name: type_mapping.get(type.__name__, 'any') for name, type in default_config_class.__annotations__.items()})
```
### Describe alternatives you considered

Creating a custom template and using something like jQuery but I really would rather not.

**Comment by aminalaee** [comment]
I think the use-case of `on_form_prefill` is different to only prepare the edit form and prefill that.
Your case is already possible with on_model_change events, why do you need another event?
https://flask-admin.readthedocs.io/en/latest/api/mod_model/#flask_admin.model.BaseModelView.on_form_prefill
https://github.com/flask-admin/flask-admin/blob/14e24c970f0ee3a29add830612eee9a0b0ba5dcc/flask_admin/model/base.py#L2165

**Comment by JettScythe** [comment]
It is not the case that `on_model_change` fills my needs. `on_model_change` only happens when someone has clicked the save button. I'm looking for something that happens when the form front end changes

**Comment by JettScythe** [comment]
I managed to solve my issue by passing a field in the form that I hide in a custom template:
```
class ToolForm(Form):
    name = SelectField("Name", choices=[(tool_name, tool_name) for tool_name in KnownTools.get_all_tool_names()])
    config = JSONField("Config", validators=[InputRequired()])
    hidden_helper = SelectField(choices=[(config[1], config[0]) for config in KnownTools.get_all_tools_configs()])
```

and prefilling the config value with
```
    document.addEventListener('DOMContentLoaded', function () {
        let nameField = document.getElementById('name');
        let toolConfigsField = document.getElementById('config');
        let hidden_helper = document.getElementById("hidden_helper");

        // Update config field when the name field changes
        nameField.addEventListener('change', function () {
            let selectedTool = nameField.value;

            // Find the corresponding option in hidden_helper based on the selectedTool name
            let matchingOption = Array.from(hidden_helper.options).find(option => {
                if (option.text === selectedTool) {
                    return option.value
                }
            });
            if (matchingOption) {
                // Parse the value of the matching option as JSON and set it to the config field
                toolConfigsField.value = JSON.stringify(matchingOption.value, null, 2);
            } else {
                // Handle the case when no matching option is found
                console.error("No matching option found for:", selectedTool);
            }
        });

        // Initial update based on the default selected value
        nameField.dispatchEvent(new Event('change'));
    });
```
