### ISSUE TITLE
Document `column_default_sort` requires strings

### ISSUE THREAD

**Issue by jerivas** [aminalaee/sqladmin#688]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

The examples in the [documentation](https://aminalaee.dev/sqladmin/configurations/#list-page) show `column_default_sort` as accepting class attributes. However, since https://github.com/aminalaee/sqladmin/commit/8f9d07d0705b241490a1f55fc69115ef598b8c50 `split()` is being called on them, and that fails unless they are strings

### Steps to reproduce the bug

Visit an admin page with default sort defined via class attributes:

```python
class UserAdmin(ModelView, model=User):
    ...
    column_default_sort = [(User.email, True), (User.name, False)]
```

### Expected behavior

The default sort is applied as defined

### Actual behavior

The server crashes because it can't `split()` class attributes

### Environment

Ubuntu 22.04, Python 3.11

### Additional context

`column_default_sort = [("email", True), ("name", False)]` works as expected

**Comment by lorg** [comment]
This bug happened to me as well, I would actually prefer the old behavior of being able to specify columns not as strings, it's less error prone (as a linter can catch typos in column names).

Also, column_sortable_list is also broken right now without a workaround

**Comment by aminalaee** [comment]
That makes sense, I think the fix is easy, I will take a look into this.

**Comment by aminalaee** [comment]
@lorg Can you clarify what is broken with `column_sortable_list`?
