### ISSUE TITLE
Menu items within categories are always visible

### ISSUE THREAD

**Issue by mishaga** [aminalaee/sqladmin#708]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

If a menu item is added to a category, it wouldn't be hidden, even if `is_visible` function of the Model/View returns `False`

### Steps to reproduce the bug

```python
class UserAdmin(ModelView, model=User):

    category = 'Accounts'

    def is_visible(self, request: Request) -> bool:
        return bool(request.session.get('username'))

    def is_accessible(self, request: Request) -> bool:
        return bool(request.session.get('username'))

admin.add_model_view(UserAdmin)
```

This menu item will be visible even if `request.session` is empty

Though, if you delete (or comment out) `category` parameter of `UserAdmin`, this menu item will be hidden for not authenticated users

### Expected behavior

Menu item is hidden

### Actual behavior

Menu item is visible

### Environment

- macOS
- Python 3.11
- SQLAlchemy 2.0.25

**Comment by mishaga** [comment]
> I think this PR is already closing this #698

#698 doesn't contain any tests :(

**Comment by KNMohamed** [comment]
@aminalaee 
Apologies, I was a version behind. I can confirm this fix works. Is there a way to put an icon on the CategoryMenu?
