### ISSUE TITLE
Use relative URLs instead of absolute URLs 

### ISSUE THREAD

**Issue by tariqjamal057** [aminalaee/sqladmin#711]
### Checklist

- [ ] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

@aminalaee, I had configured the package with application correctly in http it working file but in production it showing the below error

Mixed Content: The page at '' was loaded over HTTPS, but requested an insecure stylesheet ''. This request has been blocked; the content must be served over HTTPS.

### Environment

Production

**Comment by aminalaee** [comment]
Please check the docs https://aminalaee.dev/sqladmin/cookbook/deployment_with_https/ and there were multiple discussions around this.

**Comment by pinheiro-bruno** [comment]
@aminalaee, don't you think the current solution of forwarding the headers is a bit dangerous, since the original request, specially the authentication form uses, http?

I would rather have a way to make sure that all requests leave the browser as https

**Comment by aminalaee** [comment]
I'm not sure enforcing the HTTPS is going to be nice for some use-cases. Obviously if you are deploying on a production env you need to take care of that.
