### ISSUE TITLE
Hashing strategy for the fields such as password in the creation of a new row

### ISSUE THREAD

**Issue by agn-7** [aminalaee/sqladmin#718]
I was wondering if there would be a possibility to enforce a hashing strategy before adding a new row to a model such as the User and a specific field like the password.

Here's my admin user model:

```python
class UserAdmin(ModelView, model=models.User):
    column_list = [
        models.User.id,
        models.User.role,
        models.User.email,
        models.User.username,
    ]

    can_delete = False
```    
When I want to create a new user via `sqladmin`, the password field will be as a plain password instead of a hashed one. Therefore, I am looking for a feature to enforce the `admin` to apply a hashing method for a specific field such as password as follows:

```python
def get_hashed_password(password: str) -> str:
    return pwd_context.hash(password)

class UserAdmin(ModelView, model=models.User):
    apply_magic_method_on_field(method=get_hashed_password, field=password)  # something like this
```

- [X] There are no similar issues or pull requests for this yet.

**Comment by aminalaee** [comment]
I guess the events can do this: https://aminalaee.dev/sqladmin/configurations/#events

**Comment by agn-7** [comment]
great thanks. it works well:

```python
class UserAdmin(ModelView, model=models.User):
    column_list = [
        models.User.id,
        models.User.role,
        models.User.email,
        models.User.username,
    ]
    async def on_model_change(self, data, model, is_created, request):
        data["password"] = utils.get_hashed_password(data["password"])
```
