### ISSUE TITLE
Custom confirmation HTML

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [aminalaee/sqladmin#719]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

I want to be able to show a custom confirmation page that includes an iframe instead of just a message. I haven't looked into the source code yet, but I'd like to embed an iframe into the confirmation modal.

### Describe the solution you would like.

There are two options I can think of:
1. Point me in the right direction: there's a template rendering portion of the Python code where I can inject variables into the template. If I can override that, that's great. Then there's the template itself. In Django, I'm able to override templates via apps. Not sure how to do this here. Would be great to know how I can override where the templates are sourced from.
2. Allow adding a new Python portion that lets me do:

```python
class Admin:
    def render(self):
        html = self.extra_confirmation_template()
        return templating.RenderHTML(context={"extra_html": html})

    def extra_confirmation_template(self, **kwargs) -> str | None:
        # not sure what kwargs would be but having extra info would be nice
        return templating.RenderHTML()  # or whatever the respective Jinja function is
```

And then in the confirmation modal itself, have some HTML like:

```
{% raw %}{{ html }}{% endraw %}
```

### Describe alternatives you considered

Considered just doing it myself in an upcoming project. Haven't started it yet though and don't really understand the source code since haven't looked.

### Additional context

For context, before an object is saved, like in Django, there's a confirmation page. In this package, there's no page, rather a modal. That's fine, but for me, before saving, I need my colleagues to be able to

1. Press save
2. In the confirmation modal, I perform a fetch to the backend with the provided form data. In the backend, it'll do some processing then spit out post-processed material for confirmation (in an iframe). And my colleagues will confirm then press save.

All in all, there's a high possibility I monkeypatch

**Comment by aminalaee** [comment]
I think by the confirmation you mean the modals, which are located at https://aminalaee.dev/sqladmin/working_with_templates/#customizing-templates

And they can be customized like this:
https://aminalaee.dev/sqladmin/working_with_templates/#customizing-templates
