### ISSUE TITLE
Static file over https in AWS with ECS and LoadBalancer

### ISSUE THREAD

**Issue by Mowinski** [aminalaee/sqladmin#720]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I have a whole infrastructure in AWS.

My app are deployed on ECS as service as Docker
```CMD ["python3", "-m", "uvicorn", "rest_api.api:app", "--host", "0.0.0.0", "--port", "8000", "--forwarded-allow-ips='*'",  "--proxy-headers"]```

Then this service is targeted by target group associeted with LoadBalancer. This LB add host-forward headers and has ssl certificate. But if I try to enter my webpage over https I got cors errors on static files (they tried to hit over http). 

You can check it on https://app.narravia.com/admin
I tried everything on AWS, but this is a critical bug for me. 

### Steps to reproduce the bug

Host your project on AWS on ECS with TargetGroup and LoadBalancer with ssl

### Environment

- Latest SQLAdmin
- AWS
- Python 3.10

**Comment by aminalaee** [comment]
TBH this is a very specific deployment issue, not sure how I can help with that.
But clearly the issue is not with SQLAdmin itself rather in Uvicorn and the AWS deployment. I think you might have better chances of opening a discussion there.

**Comment by neara** [comment]
Having same issue:  https://github.com/aminalaee/sqladmin/issues/721
My details: https://github.com/aminalaee/sqladmin/issues/721#issuecomment-1978755097

One deployment works, one doesn't. So far, looks like an issue with SQLAdmin itself. Docs app served from the same FastAPI server, knows that it's https and works properly. 
I outputted the headers and sql admin app is getting the `x-forwarded-proto=https`, it should know to use the https urls. 

Please advise what might be the issue.

**Comment by neara** [comment]
I tried adding `--forwarded-allow-ips='*'` and `--proxy-headers` and still same result. 
Also tried this:
```
CMD ["gunicorn", "app.main:app", "--workers=4", "--worker-class=app.uvcorn_worker.CustomUvicornWorker", "--bind=0.0.0.0:8000", "--forwarded-allow-ips='*'", "--proxy-allow-from='*'", "--proxy-protocol"]
```

with the custom worker:

```
from uvicorn.workers import UvicornWorker


class CustomUvicornWorker(UvicornWorker):
    CONFIG_KWARGS = {"proxy_headers": True}
```

All the same.

Curl on `/admin` returns location as http.

Headers are passed to the admin app and indicate https.

**Comment by NightSkySK** [comment]
How did you assign SSL certificates to your page. Maybe there is a problem ...

**Comment by neara** [comment]
The SSL is created via ACM, validated via DNS. Browsers trust the license. 

Is there any way to force https?

**Comment by NightSkySK** [comment]
Contact me via form at https://www.mspacelock.com/contact if you wish we can do some troubleshooting via call or email and compare our configurations

**Comment by neara** [comment]
Thanks for the offer. Still don't know what's the issue exactly. I bypassed it by setting up FastAPI app with ssl + updating the target group to use https for the traffic with the container.

**Comment by acuku** [comment]
@neara what would you think of a solution where you inject a middleware on the Admin class initialization and in the dispatch method to change the scheme from http to https inside the fastapi request.
`request.scope["scheme"] = "https"`

**Comment by SrDonEmilio** [comment]
I'm having the same issue. I think that happens because the python project starts as HTTP, without a certificate, so the function url_for in base.html generates a url with http. The python project doesn't know that the ALB assigns a certificate.

Right now I can't try and test, but I came up with the following ideas:

1. Use custom templates, with the same login.html (and others templates) but a custom base.html

2. Manually overwrite the starlette route "admin:statics"

**Comment by vishalbollu** [comment]
I had a similar set up with webserver deployed on ECS behind an ALB with a cert. The static files were being served from http://. After updating the dockerfile command to 
```
CMD ["uvicorn", "...",  "--proxy-headers", "--forwarded-allow-ips", "*"]
```

It started working for me - note the lack of quotes around `*`.

See referenced suggestion from a starlette thread: https://github.com/encode/starlette/issues/538#issuecomment-1724157740

**Comment by onejgordon** [comment]
We're seeing this too, and it's blocking deploys to EBS/EC2 where we're using the Docker platform and running gunicorn with UvicornWorker similar to https://github.com/aminalaee/sqladmin/issues/720#issuecomment-1978934149. 

Anyone found a workaround?

**Comment by aminalaee** [comment]
@onejgordon Didn't what @vishalbollu mention work?

**Comment by onejgordon** [comment]
Thanks for your response @aminalaee, in fact we did get this working using:

```
class CustomUvicornWorker(UvicornWorker):
    CONFIG_KWARGS = {
        "proxy_headers": True,
        "forwarded_allow_ips": "*"
    }
```

**Comment by aminalaee** [comment]
@Mowinski can you also confirm this has worked for you so we can close this?

**Comment by Mowinski** [comment]
Just look at your own eyes - https://app.narravia.com/admin/ 

Thanks guys, it is working :) 
Just: 
```CMD ["poetry", "run", "uvicorn", "rest_api.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--forwarded-allow-ips", "*",  "--proxy-headers"]```

**Comment by bathwaterpizza** [comment]
> I had a similar set up with webserver deployed on ECS behind an ALB with a cert. The static files were being served from http:// which caused issues when the rest of the webserver was using https://.
> 
> After updating the dockerfile command to
> 
> ```
> CMD ["uvicorn", "...",  "--proxy-headers", "--forwarded-allow-ips", "*"]
> ```
> 
> It started working for me - note the lack of quotes around `*`.
> 
> See referenced suggestion from a starlette thread: [encode/starlette#538 (comment)](https://github.com/encode/starlette/issues/538#issuecomment-1724157740)

This simple change just solved my entire life problems, thank you.
