### ISSUE TITLE
Unexpected main page view

### ISSUE THREAD

**Issue by utikpuhlik** [aminalaee/sqladmin#728]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I have a FastAPI application with `asyncpg=0.29.0`, `sqlalchemy=2.0.27` and `sqladmin=0.16.1`
When I'm trying to open `127.0.0.1:8000/admin` I have a blank page with dummy stuff, even though I didn't include any Product models to admin view, **only the User one** (details are in steps to reproduce):
![image](https://github.com/aminalaee/sqladmin/assets/85949628/3f375a0b-6088-4083-b992-09e7e3382a34)

Any thoughts?

Here's my Product model, just in case:
```python
class Product(Base):
    __tablename__ = "product"
    id: Mapped[uuid:UUID] = mapped_column(UUID(as_uuid=True), default=uuid.uuid4, primary_key=True)
    name: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(String, nullable=True)
    price: Mapped[float] = mapped_column(Double, nullable=False)
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=True, default=datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(TIMESTAMP(timezone=True), nullable=True, default=datetime.now(timezone.utc), onupdate=datetime.now(timezone.utc))

    images = relationship("ProductImage", backref="product")
```

### Steps to reproduce the bug

Here's `main.py`:
```python
from fastapi import FastAPI
from sqladmin import Admin, ModelView
from app.database import engine
from app.api.models.users import User

app = FastAPI(title="Bakery App", version="1.0")

admin = Admin(app, engine)

class UserAdmin(ModelView, model=User):
    column_list = [User.id, User.email]
    column_details_exclude_list = [User.hashed_password]


admin.add_view(UserAdmin)
```

My ORM model:
```python
class User(Base):
    __tablename__ = "user"
    id: Mapped[uuid:UUID] = mapped_column(UUID(as_uuid=True), default=uuid.uuid4, primary_key=True)
    email: Mapped[str] = mapped_column(String, nullable=False)
    hashed_password: Mapped[str] = mapped_column(String, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    is_superuser: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    is_verified: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
```

Engine:
```python
engine = create_async_engine(
    global_settings.asyncpg_url.unicode_string(),
    future=True,
    pool_pre_ping=True,
)
```

### Expected behavior

Admin panel like in documentation screenshots

### Actual behavior

When I'm trying to open `127.0.0.1:8000/admin` I have a blank page with dummy stuff, even though I didn't include any Product models to admin view, only User model:
![image](https://github.com/aminalaee/sqladmin/assets/85949628/3f375a0b-6088-4083-b992-09e7e3382a34)

### Environment

Windows / Python 3.11 / SQLAdmin 0.16.1

### Additional context

I also planning to use https://github.com/fastapi-admin/fastapi-admin library but for now just using a base sqlalchemy model for User

**Comment by aminalaee** [comment]
I can't seem to reproduce this, two questions:
- Are you working on this locally? I can see that CSS files are not loaded properly.
- And User has no relation to the Product as far as I can see, are you sure you are not adding it in another place to the admin?

**Comment by aminalaee** [comment]
I think you need to check the network tab to see why CSS is not loading.
And something looks very strange in your project because <title></title> HTML tag should be `Admin`, not `ProductList` maybe https://github.com/utikpuhlik/bakery-fastapi/blob/main/app/main.py#L90 this is messing things up

**Comment by utikpuhlik** [comment]
So I really don't know what was wrong but after project recreation admin panel works fine. **I think stuff relating to jinja2 and static files is responsible for this issue**. Nevertheless, thank you for your cooperation!

**Comment by utikpuhlik** [comment]
Just for info, start a new project helped me to resolve this problem
