### ISSUE TITLE
form_overrides doesn't work

### ISSUE THREAD

**Issue by Ae-Mc** [aminalaee/sqladmin#736]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

form_overrides doesn't work at all

### Environment

- Ubuntu 20.04/Python 3.11/0.16.1

**Comment by aminalaee** [comment]
You need to be more specific, please update your issue description if you want people to help you.

**Comment by Ae-Mc** [comment]
Sorry. I'm not sorry what have I done different, but I tried to use it again and error disappeared.
