### ISSUE TITLE
sqladmin + jinja templates conflict index.html

### ISSUE THREAD

**Issue by dotparsed** [aminalaee/sqladmin#747]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

for html static files jinja use folder "templates" , but if i create index.html  sqladmin redirect to this page  (Strange behavior)

### Steps to reproduce the bug

1)Create new project
2) pip install fastapi uvicorn sqladmin
3) create basic main.py with sqladmin
4) create folder templates/index.html   (this file used for main pages not admin panels)
5) open http://127.0.0.1:8000/admin    ->  redirect to index.html

### Expected behavior

don't use index.html for admin page.   maybe change to admin.html  

### Environment

windows python venv fasapi uvicorn sqladmin pycharm

**Comment by hasansezertasan** [comment]
I believe SQLAdmin could use a file structure for templates similar to Flask Admin and Flask AppBuilder.

Meaning, move every template that SQLAdmin use to `templates/sqladmin/` from `templates/`.

This will remove the conflict.


Or you can just rename your `index.html`

**Comment by aminalaee** [comment]
@hasansezertasan I think that's a reasonable approach, feel free to submit the PR if you like.

**Comment by hasansezertasan** [comment]
> @hasansezertasan I think that's a reasonable approach, feel free to submit the PR if you like.

I'll work on it, thanks 😇.
