### ISSUE TITLE
Raised value error

### ISSUE THREAD

**Issue by BhuwanPandey** [aminalaee/sqladmin#751]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Raised valueerror when I passed string value for queryparameter page and pagesize

### Steps to reproduce the bug

To reproduce this issue when I pass page=ab and pagesize=rm like 
/admin/user/list?page=ab&pageSize=rm  

### Expected behavior

When user pass any value other than integer 
what I expected to
1. Either raised error message like
{
  "error": {
    "page": "value is not a valid integer",
     "pagesize": "value is not a valid integer",
  }
}
OR
2. show the default value like page=1 and pagesize=10

### Environment

window 11 /python 3.11 /

### Additional context

 Based on the approach that I provided which you think is more appropriate. For me, first one give more sense. 
If you think , Is this the actual issue. 
If so, I will be happy to contribute on this issue.

**Comment by aminalaee** [comment]
hey, what does page=rm mean? these are supposed to be numbers as the errors suggests.

**Comment by BhuwanPandey** [comment]
> hey, what does page=rm mean? these are supposed to be numbers as the errors suggests.

Page and Pagesize supposed to be number but when user pass value of  page and pagesize to some string value other than integervalue
It says (Internal server Error)
https://sqladmin-demo.aminalaee.dev/admin/address/list?page=somevalue
https://sqladmin-demo.aminalaee.dev/admin/address/list?page=2&pageSize=somevalue

**Comment by aminalaee** [comment]
Yeah I think defaulting to the first page is fine. Feel free to create a PR for that.

**Comment by hasansezertasan** [comment]
I also think that these parameters should have default values.

@BhuwanPandey looking forward to see your PR!

**Comment by aminalaee** [comment]
Closed by #752
