### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: list.html

### ISSUE THREAD

**Issue by JakNowy** [aminalaee/sqladmin#768]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I am overriding the list template in my admin:

```
{% extends "list.html" %} {% block content %} {{ super() }}
<head>
    <style>
        td {max-width: 250px; text-overflow: ellipsis; overflow: hidden;}
    </style>
</head>

{% endblock %}
```

It used to work fine until recent release. Currently accessing list view raises `jinja2.exceptions.TemplateNotFound: list.html` in `{% extends "list.html" %} {% block content %} {{ super() }}`. The template seems to still be present in the source code on master branch.

### Environment

Linux, python3.11, newest app version.

**Comment by JakNowy** [comment]
This was caused by https://github.com/aminalaee/sqladmin/pull/748, I solved it by adding sqladmin/ prefix in `extends "sqladmin/list.html`.

Leaving the post in case someone else runs into same issue,

**Comment by aminalaee** [comment]
Yes you are right, that is one of the changes that the templates are moved to have a better experience overriding.

**Comment by advenn** [comment]
I have similar problem, i was just learning the behaviour of extending. my code:
custom-detail.html in views folder. the folder is recognized inside my own jinja env 
````
{% extends "sqladmin/details.html" %}
{% block content %}
    {{ super() }}

    <p>Custom html</p>
{% endblock %}
```
as given on docs. the problem is jinja can't find custom-detail.html, i tried <filename>, <path from project root> ,<absolute -path> none of them couldn't help. what should i do in this case?

**Comment by hasansezertasan** [comment]
Anyone who searches `TemplateNotFound` error in this repo will find this issue, no need to keep it open.
