### ISSUE TITLE
[feature request] Custom login page

### ISSUE THREAD

**Issue by avtakhov** [aminalaee/sqladmin#778]
### Checklist

- [ ] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

I want to be able to create custom login page, but i can't because there is `assert self.authentication_backend is not None`

**Comment by hasansezertasan** [comment]
> I want to be able to create custom login page, but i can't because there is `assert self.authentication_backend is not None`

You can always override the login template.
