### ISSUE TITLE
sqlalchemy column_property should be ignore when create/update

### ISSUE THREAD

**Issue by wangxin688** [aminalaee/sqladmin#789]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

minimal example
```python3

class Site(Base, AuditUserMixin, AuditLogMixin):
    """Office, Campus or data center"""

    __tablename__ = "site"
    __search_fields__ = {"name", "site_code", "physical_address"}
    __visible_name__ = {"en_US": "Site", "zh_CN": "站点"}
    id: Mapped[int_pk]
    name: Mapped[str] = mapped_column(unique=True)
    site_code: Mapped[str] = mapped_column(unique=True, index=True)
    site_group_id: Mapped[int | None] = mapped_column(ForeignKey("site_group.id", ondelete="RESTRICT"))
    site_group: Mapped["SiteGroup"] = relationship(back_populates="site")

class SiteGroup(Base, AuditUserMixin):
    __tablename__ = "site_group"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(unique=True)
    description: Mapped[str | None]
    site: Mapped[list["Site"]] = relationship(back_populates="site_group")
    site_count: Mapped[int] = column_property(
        select(func.count(Site.id)).where(Site.site_group_id == id).scalar_subquery(),
        deferred=True,
    )
```
when `column_property` added to Base class. create/update will broken for 
500 Server Error
AttributeError: Neither 'Label' object nor 'Comparator' object has an attribute 'nullable'
``

### Steps to reproduce the bug

full stack trace:
500 Server Error
AttributeError: Neither 'Label' object nor 'Comparator' object has an attribute 'nullable'
Traceback

File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py, line 1498, in __getattr__‒
1495.         try:

1496.             return getattr(self.comparator, key)

1497.         except AttributeError as err:

1498.             raise AttributeError(

1499.                 "Neither %r object nor %r object has an attribute %r"

1500.                 % (

1501.                     type(self).__name__,

File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/sqladmin/forms.py, line 187, in _prepare_column+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/sqladmin/forms.py, line 150, in _prepare_kwargs+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/sqladmin/forms.py, line 291, in convert+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/sqladmin/forms.py, line 627, in get_model_form+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/sqladmin/models.py, line 1021, in scaffold_form+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/sqladmin/application.py, line 509, in create+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/sqladmin/authentication.py, line 68, in wrapper_decorator+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/routing.py, line 72, in app+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py, line 53, in wrapped_app+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py, line 64, in wrapped_app+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/routing.py, line 77, in app+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/routing.py, line 297, in handle+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/routing.py, line 776, in app+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/routing.py, line 756, in __call__+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py, line 53, in wrapped_app+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py, line 64, in wrapped_app+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py, line 65, in __call__+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/middleware/sessions.py, line 85, in __call__+
File /Users/jeffry/Coding/netsight/backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py, line 164, in __call__+

### Environment

MACOS 14.2.1
sqlalchemy version: 2.0.31

**Comment by wangxin688** [comment]
full model define see:
https://github.com/wangxin688/netsight/blob/main/backend/src/features/org/models.py

**Comment by wangxin688** [comment]
I guess something like this should be set, only if ORM model's field is Column. it should be set
```
    @classmethod
    def should_column_be_set(cls, column: Any) -> bool:
        if not isinstance(column, Column):
            return False

        if not cls.__set_primary_key__ and column.primary_key:
            return False

        return bool(cls.__set_foreign_keys__ or not column.foreign_keys)
```

**Comment by hasansezertasan** [comment]
Related: jowilf/starlette-admin#408

**Comment by wangxin688** [comment]
> Related: [jowilf/starlette-admin#408](https://github.com/jowilf/starlette-admin/pull/408)

yes I have checked this. see edit/create is work. but if I add column_property field to fields, it will raise greenlet error. subquery cannot load automatically

**Comment by aminalaee** [comment]
> but if I add column_property field to fields

I'm not sure if I get this right, by fields you mean form fields? or display fields?

**Comment by wangxin688** [comment]
> > but if I add column_property field to fields
> 
> I'm not sure if I get this right, by fields you mean form fields? or display fields? So create/edit forms are working fine?

display works pretty fine. edit/create forms raise the error

**Comment by wangxin688** [comment]
> Related: [jowilf/starlette-admin#408](https://github.com/jowilf/starlette-admin/pull/408)

@hasansezertasan seems it's not fully support `column_property` for subquery in async engine. you can check my orm mode definition in repo link.

**Comment by aminalaee** [comment]
I think @hasansezertasan is pointing to another project which is a little bit confusing 😄 
I will create a simple fix for the PR to see if it works.

**Comment by hasansezertasan** [comment]
> I think @hasansezertasan is pointing to another project which is a little bit confusing 😄.

I just wanted to address it because it kinda solves this problem 😅.

**Comment by aminalaee** [comment]
No worries, if it helps anyone I'm fine with it. I just thought the OP didn't know it was not the same project.
