### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by jrlopes2005** [aminalaee/sqladmin#8]
Hi.

I installed it with pip but i cant import "from sqladmin import Admin, ModelAdmin"... its not working.

Any help?

Thanks

**Comment by aminalaee** [comment]
Hey,

Yes I haven't actually released this yet, some basic functionality is available though,
which you can see in the demo.

You can install it from the git repository using pip for now. Let me know if that doesn't work out for you.

Something like this should do it:
```
https://github.com/aminalaee/sqladmin.git
```

**Comment by aminalaee** [comment]
I've also released version `0.1.0`. So it's safe to close this now.

Any feedback would be appreciated 👍
