### ISSUE TITLE
Redirect to custom url after creation 

### ISSUE THREAD

**Issue by Mowinski** [aminalaee/sqladmin#804]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Right now I want to redirect to png file, based on object or just to it's details view. 

### Describe the solution you would like.

A method that receive request object and created object and returns string or URL object

**Comment by aminalaee** [comment]
I think you should probably override `get_save_redirect_url` on a custom `Admin` class here: https://github.com/aminalaee/sqladmin/blob/a5f6d13f261f643e768fb35ce8559869d6d8273e/sqladmin/application.py#L665
