### ISSUE TITLE
Document update may be required to resolve DeprecationWarning from Starlette

### ISSUE THREAD

**Issue by a4rcvv** [aminalaee/sqladmin#809]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

The example code of [Using OAuth](https://aminalaee.dev/sqladmin/authentication/#using-oauth) causes `DeprecationWarning: The route decorator is deprecated, and will be removed in version 1.0.0. Refer to https://www.starlette.io/routing/ for the recommended approach.`

reference: https://github.com/encode/starlette/pull/1897

### Describe the solution you would like.

I think the source code like below is better to avoid the warning.

```py
# @admin.app.route("/auth/google")
async def login_google(request: Request) -> Response:
    token = await google.authorize_access_token(request)
    user = token.get('userinfo')
    if user:
        request.session['user'] = user
    return RedirectResponse(request.url_for("admin:index"))

admin.app.router.add_route("/auth/google", login_google)  # added
```

**Comment by aminalaee** [comment]
Sure, feel free to create a PR for this 👍
