### ISSUE TITLE
Add an ability to add forms into actions

### ISSUE THREAD

**Issue by badger-py** [aminalaee/sqladmin#840]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

I want to be able to ask the admin panel user for a string when they chose to use an actions. in my specific case, it will be used to let the admin send the message to the user selected

### Describe the solution you would like.

Some way to provide a form for the action and get this form when processing the action

### Describe alternatives you considered

Creating a custom view or even a separate page but it will be much more comfortable, if this was just action functionality

**Comment by aminalaee** [comment]
https://aminalaee.dev/sqladmin/configurations/#custom-action
