### ISSUE TITLE
Icon for category

### ISSUE THREAD

**Issue by sheldygg** [aminalaee/sqladmin#845]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

I want add icon for category

### Describe the solution you would like.

We can add `category_icon` to `BaseView`

**Comment by sheldygg** [comment]
@aminabbasov I can create PR, I want your confirmation

**Comment by aminabbasov** [comment]
> @aminabbasov I can create PR, I want your confirmation

Hey mate! Did you mean to tag me? I think you might be looking for `aminalaee` – our nicknames are pretty similar =)

**Comment by sheldygg** [comment]
> > @aminabbasov I can create PR, I want your confirmation
> 
> Hey mate! Did you mean to tag me? I think you might be looking for `aminalaee` – our nicknames are pretty similar =)

Oh sorry =), yes I wanted to ping @aminalaee, anyway PR is already created
