### ISSUE TITLE
Way to display images in the list table

### ISSUE THREAD

**Issue by avaziman** [aminalaee/sqladmin#850]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

Given a table that contains a URL for an image, I would like to visually see the images instead of their URLs in the SQLADMIN table.

**Comment by netcmcc** [comment]
Use javascript in the template to rewrite a cell, identify the image link starting with http and convert it into img

**Comment by aliereno** [comment]
You can write custom column formatter for detail page.

```

def format_image_url(model, attribute) -> Markup:
    return Markup(f'<img src="{getattr(model, attribute)}" alt="Description of the image" />')

```

Then use it in model view;

```
class UserAdmin(ModelView, model=User):
    column_formatters_detail = {
        "image": format_image_url,
    }
```

**Comment by avaziman** [comment]
hey that works great! thanks a lot
