### ISSUE TITLE
Problem with html and js when deploying to Kubernetes

### ISSUE THREAD

**Issue by seldish-og** [aminalaee/sqladmin#851]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When i run in docker my app with your admin library all works fine, design looks fine. But when i deploy this to kuber, somehow css and js not working and i see only row html. Core logic works ok but design not working

Have this error on frontend page: Mixed Content: The page at 'https://resources.app.1.dev.hedge-fund.tech/admin/login' was loaded over HTTPS, but requested an insecure stylesheet 'http://resources.app.1.dev.hedge-fund.tech/admin/statics/css/tabler.min.css'. This request has been blocked; the content must be served over HTTPS.

### Environment

Latest Python and latest SqlAdmin

**Comment by aminalaee** [comment]
https://aminalaee.dev/sqladmin/cookbook/deployment_with_https/

This is already discussed in the issues, you can find the answer there too.
