### ISSUE TITLE
Boolean field checkbox doesn't work

### ISSUE THREAD

**Issue by aminalaee** [aminalaee/sqladmin#87]
### Discussed in https://github.com/aminalaee/sqladmin/discussions/86

<div type='discussions-op-text'>

<sup>Originally posted by **maxiaojunwolf** March 15, 2022</sup>
here is my ORM Field:
 
        picture = Column(Boolean, default=False)

![20220315-224244](https://user-images.githubusercontent.com/34365493/158403156-d0b319a7-1c87-4dd3-9733-f3dbd5a89b2f.png)
</div>

**Comment by Args** [comment]
I encountered the same problem in version 0.1.6.

**Comment by aminalaee** [comment]
Yes you're right. This will be available 0.1.7 in a few days.

**Comment by Args** [comment]
Thanks a lot~

**Comment by Rivosoa** [comment]
I encountered this problem in version 0.1.11.
I had to specify the class on form_widget_args to make it work
`form_widget_args = dict(active={"class": "form-check-input"})`

**Comment by aminalaee** [comment]
This should be already included with the Boolean, if you think otherwise feel free to create a PR for the fix.

**Comment by Rivosoa** [comment]
> This should be already included with the Boolean, if you think otherwise feel free to create a PR for the fix.

I don't have much time now to create a PR for it. But I searched it a bit and found the problem happens when you override a field as a BooleanField.
