### ISSUE TITLE
Add "form_columns" concept

### ISSUE THREAD

**Issue by dwreeves** [aminalaee/sqladmin#96]
### Checklist

- [X] There are no similar issues or pull requests for this yet.

### Is your feature related to a problem? Please describe.

I am trying to emulate all the functionality of a Flask-Admin panel I made using SQLAdmin. The Flask website I'm attempting to emulate is open source and available [here](https://github.com/codeforboston/flagging). It is able to be deployed in "demo" mode to Heroku so anyone can run it. (set `FLASK_ENV=demo` as you deploy it).

So far, I am running into an issue with complicated lazy relationships. Take the following SQLModel as an example:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/31971762/159168988-a68cd782-acf9-4dd2-a49a-5818b66243fe.png">

This is a SQLModel with lots of complicated relationships at the bottom, but these relationships do not need to be manually defined in the admin panel. In the case of `latest_prediction` it's resolved via `max(timestamp)`. In the case of `all_predictions`, it is a many-to-one relationship that is resolved through an associative entity (named `Reach`).

In Flask-Admin, I would work around this by explicitly defining `form_columns` and excluding these complicated fields. And for Flask-Admin, this is what I get for my `Boathouse` entity type:

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/31971762/159168913-9a5ced3f-1c04-45e5-8415-de1351c71938.png">

But due to lack of a `form_columns`, I cannot make this happen in SQLAdmin. It is forcing me to include these columns, which means I effectively cannot use both SQLAdmin and these complicated fields at the same time:

![image](https://user-images.githubusercontent.com/31971762/159168961-4180cc62-6c43-4ba5-8341-ebade63fabc5.png)

### Describe the solution you would like.

Flask-Admin has a concept called `form_columns` for its `ModelView` class. The `form_columns` attribute controls which columns that WTForms creates fields for.

This is a good catchall solution for many problems because it lets users avoid any issues relating to fields that do not need to be assigned as part of the initialization of an object (e.g. optional fields, fields with defaults, complicated relationships, and more).

Flask-Admin implements `form_columns` here, primarily: https://github.com/flask-admin/flask-admin/blob/7cff9c742d44d42a8d3495c73a6d71381c796396/flask_admin/contrib/sqla/form.py#L94

---

Right now, the function `sqladmin.forms.get_model_form` can handle inclusion or exclusion of fields. However, this functionality is not used. So the function would need to be passed a `form_columns`, or similar, from the ModelAdmin object.

This should not be too hard to implement-- just add `form_columns` to the ModelAdmin class (`form_columns` is adherent to the Flask-Admin API and is thus preferrable, albeit another naming such as `form_column_list` would be acceptable if deviations are allowed), and have that be passed through the `scaffold_form()` method.

**Comment by aminalaee** [comment]
Hi,

Thanks a lot for the detailed explanation. Yes this makes sense and I've tried to keep th API compatible with Flask-Admin.

Feel free to create a PR for this if you feel like it.

**Comment by dwreeves** [comment]
PR is up. All I am missing is `column_labels` support for the forms.

**Comment by aminalaee** [comment]
Thanks to @dwreeves this is merged.
